import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {generateScoreInputs} from '../src/lib/radar-score-input/generator.ts';
import {lockExecutionSet,executeLockedSet,assertExecutionReplay} from '../src/lib/radar-score-action-closure/execution.mjs';
import {configureProductionAdapter} from '../src/lib/radar-judgment/production-adapter.mjs';
import {readCommittedRegistryContext} from '../src/lib/radar-score-action-closure/registry-context.mjs';
import {sha256,canonical} from '../src/lib/radar-judgment/provider.mjs';
import {buildObservationIdentity} from '../src/lib/radar-observation-identity.mjs';
import {buildEventFingerprint} from '../src/lib/radar-event-identity.mjs';
const at='2026-10-04T00:00:00Z';
async function item(){
 const candidate={radar:'AI',sourceName:'OpenAI News',title:'Isolated test release',sourceUrl:'https://example.org/test-release',observedAt:at,version:'1',intendedUsage:'isolated-test',capabilityScope:['test-capability'],evidence:[{evidenceRef:'test-evidence',sourceName:'OpenAI News',sourceAuthority:'official',sourceUrl:'https://example.org/test-release',observedAt:at}],eventIdentity:{entity:'isolated-test',canonicalEventType:'model-release',eventKey:'isolated-test:model-release:1',eventIdentifier:'1',evidenceRefs:['test-evidence'],identityEngineVersion:'2.1.2'}};
 const registryState={committed:true,registryWriteStatus:'COMMITTED',eventKey:candidate.eventIdentity.eventKey,observationId:'isolated-obs',transactionId:'isolated-transaction',eventState:'NEW',duplicate:false,policyVersion:'1.0'};
 const context={generatedAt:at,trackedEnvironmentRef:'isolated-test-env',relevanceResolution:{value:'DIRECT',authority:'SCORE_INPUT_GENERATION_POLICY_2.1.0',policyVersion:'2.1.0',ruleId:'isolated-test-rule',evidenceRefs:['test-evidence']},momentumResolution:{value:7,authority:'SCORE_INPUT_GENERATION_POLICY_2.1.0',policyVersion:'2.1.0',ruleId:'isolated-test-rule',evidenceRefs:['test-evidence']},securityAssessment:{gate:'N/A',authority:'SECURITY_GATE_POLICY',policyVersion:'1.0',ruleId:'SECURITY_GATE_NOT_APPLICABLE',evidenceRefs:['test-evidence']},deterministicRiskResolution:{status:'DECISIVE',value:'normal',authority:'RISK_POLICY_1.0',policyVersion:'1.0',ruleId:'isolated-test-rule',evidenceRefs:['test-evidence']},priorValidationLookup:{complete:true,healthy:true,authority:'EXPLICIT_HUMAN_VALIDATION',resolution:'NO_ACTIVE_RECORD',registryVersion:'isolated-test',evidenceRefs:['test-evidence'],completeLookupReceipt:'test-evidence'},registryResult:registryState};
 const generated=await generateScoreInputs(candidate,context,()=>({value:8,rubricVersion:'1.0',modelId:'ISOLATED_SYNTHETIC_PROTOCOL_TEST',provider:'TEST_ONLY',generationConfigRef:'isolated-test',generationConfidence:1,evidenceRefs:['test-evidence']}));
 assert.equal(generated.status,'SCORE_READY',JSON.stringify(generated.generationFailures));
 return {eventKey:candidate.eventIdentity.eventKey,observationId:'isolated-obs',source:'ISOLATED_SYNTHETIC_TEST_ONLY',scoreInput:{inputs:generated.inputs,provenance:generated.provenance},securityResult:{status:'NOT_APPLICABLE',gateClass:'N/A',scoreEligible:true,escalationResult:'NOT_EVALUATED'},registryState};
}
test('isolated locked Score/Action execution exactly replays; no publication',async()=>{const locked=lockExecutionSet([await item()]);const a=executeLockedSet(locked);assert.equal(a.count,1);assert.equal(a.registryWrites,0);assert.equal(a.publisherCalls,0);assert.equal(a.records[0].output.publicationDecision,'NONE');assert.equal(assertExecutionReplay(a,executeLockedSet(locked)).status,'PASS');});
test('empty locked set is NOT_APPLICABLE, not real deterministic execution evidence',()=>{const m=lockExecutionSet([]);const a=executeLockedSet(m);assert.equal(a.scoreCalls,0);assert.equal(a.actionCalls,0);assert.equal(assertExecutionReplay(a,executeLockedSet(m)).status,'NOT_APPLICABLE');});
for(const [name,mutate]of Object.entries({score_input_corruption:r=>{delete r.scoreInput.inputs.impact;},score_policy_input_mismatch:r=>{r.scoreInput.provenance.impact.value=9;},unknown_enum:r=>{r.scoreInput.inputs.risk='invented';r.scoreInput.provenance.risk.value='invented';},security_unresolved:r=>{r.securityResult.status='UNRESOLVED';},registry_state_mismatch:r=>{r.registryState.eventKey='wrong';},duplicate_state_mismatch:r=>{r.registryState.duplicate=true;},human_lookup_unavailable:r=>{delete r.scoreInput.inputs.priorValidation;delete r.scoreInput.provenance.priorValidation;},conflicting_validation:r=>{r.scoreInput.provenance.priorValidation.humanValidationRecord.resolution='CONFLICT';delete r.scoreInput.inputs.priorValidation;},provider_provenance_failure:r=>{delete r.scoreInput.provenance.confidence.modelId;}}))test('execution fail closed: '+name,async()=>{const r=await item();mutate(r);assert.throws(()=>lockExecutionSet([r]));});
test('locked input/hash/policy tamper and replay mismatch fail closed',async()=>{const m=lockExecutionSet([await item()]);for(const mutate of [x=>x.records[0].scoreInput.inputs.impact=9,x=>x.policyVersion='2.2',x=>x.records[0].scoreInputHash=sha256('wrong')]){const x=structuredClone(m);mutate(x);assert.throws(()=>executeLockedSet(x));}const a=executeLockedSet(m),b=structuredClone(a);b.records[0].action='adopt';assert.throws(()=>assertExecutionReplay(a,b),/REPLAY_MISMATCH/);});
test('duplicate execution identity cannot be locked',async()=>{const r=await item();assert.throws(()=>lockExecutionSet([r,r]),/DUPLICATE_EXECUTION/);});
async function adapterFixture(fn){const root=await mkdtemp(join(tmpdir(),'horizon-adapter-test-'));try{const path=join(root,'config.json');await writeFile(path,JSON.stringify({agents:{defaults:{model:{primary:'isolated/test-model'}}},models:{providers:{isolated:{api:'anthropic-messages',baseUrl:'https://example.org/anthropic',apiKey:'ISOLATED_TEST_CREDENTIAL',models:[{id:'test-model'}]}}}}));await fn(path);}finally{await rm(root,{recursive:true,force:true});}}
test('production transport uses exact configured model and structured tool; safe metadata excludes secrets',async()=>adapterFixture(async path=>{let called=false;const p=await configureProductionAdapter(path,{fetchImpl:async(url,options)=>{called=true;assert.equal(url,'https://example.org/anthropic/v1/messages');const body=JSON.parse(options.body);assert.equal(body.model,'test-model');assert.equal(body.tool_choice.name,'submit_judgment');assert.equal(options.redirect,'error');return {ok:true,text:async()=>JSON.stringify({stop_reason:'tool_use',content:[{type:'tool_use',name:'submit_judgment',input:{synthetic:'TEST_ONLY'}}]})};}});assert.ok(!JSON.stringify(p.metadata).includes('ISOLATED_TEST_CREDENTIAL'));assert.deepEqual(await p.adapter.execute({frozenRubric:{}},{signal:new AbortController().signal,requestFingerprint:sha256('test')}),{synthetic:'TEST_ONLY'});assert.ok(called);assert.equal(p.getCalls(),1);}));
for(const name of ['invalid_response','duplicate_result','http_error'])test('real transport adapter failure: '+name,async()=>adapterFixture(async path=>{const raw=name==='invalid_response'?'free-form text':JSON.stringify({stop_reason:'tool_use',content:[{type:'tool_use',name:'submit_judgment',input:{}},{type:'tool_use',name:'submit_judgment',input:{}}]});const p=await configureProductionAdapter(path,{fetchImpl:async()=>({ok:name!=='http_error',text:async()=>raw})});await assert.rejects(()=>p.adapter.execute({},{signal:new AbortController().signal,requestFingerprint:sha256('test')}));}));
test('read-only committed Registry binding verifies pair, journal and post-commit audit',async()=>{const root=await mkdtemp(join(tmpdir(),'horizon-readonly-registry-'));try{
 const key='isolated-test:version-update:1',fp=buildEventFingerprint({});const event={eventKey:key,entity:'isolated-test',canonicalEventType:'version-update',firstObservedAt:at,lastObservedAt:at,occurrences:1,latestFingerprint:fp,fingerprintHistory:[{fingerprint:fp,eventState:'NEW',observedAt:at}],lastEventState:'NEW',radars:['dev'],observationIds:[],createdAt:at,updatedAt:at};const obs={eventKey:key,radar:'dev',sourceName:'Claude Code Changelog',sourceLevel:'official',sourceAuthority:'official',sourceUrl:'https://example.org/test',canonicalSourceUrl:'https://example.org/test',observedAt:at,firstObservedAt:at,lastObservedAt:at,createdAt:at};obs.observationId=buildObservationIdentity(obs).observationId;event.observationIds=[obs.observationId];const events=JSON.stringify(event)+'\n',observations=JSON.stringify(obs)+'\n';await writeFile(join(root,'radar-event-registry.jsonl'),events);await writeFile(join(root,'radar-observation-registry.jsonl'),observations);await writeFile(join(root,'radar-registry-transaction.json'),JSON.stringify({state:'COMMITTED',transactionId:'test-tx',eventFinalSha256:sha256(events),observationFinalSha256:sha256(observations)}));const {mkdir}=await import('node:fs/promises');await mkdir(join(root,'audit'));const receipt={operation:'WRITE_RESULT',success:true,transactionId:'test-tx',eventKey:key,observationId:obs.observationId,disposition:'NEW_EVENT',source:{radar:'DEV',sourceName:obs.sourceName},evidenceReference:obs.sourceUrl};const path=join(root,'audit/registry-operations.jsonl');await writeFile(path,JSON.stringify(receipt)+'\n');const original=await readFile(path);assert.equal((await readCommittedRegistryContext(root)).records[0].registryResult.duplicate,false);assert.deepEqual(await readFile(path),original);receipt.disposition='DUPLICATE_OBSERVATION';await writeFile(path,JSON.stringify(receipt)+'\n');await assert.rejects(()=>readCommittedRegistryContext(root),/STATE_MISMATCH/);
}finally{await rm(root,{recursive:true,force:true});}});
test('production adapter boundary rejects timeout, structured provenance failure and rubric mismatch before any Score',async()=>adapterFixture(async path=>{
 const {loadRubric,PINS,evaluateJudgment}=await import('../src/lib/radar-judgment/provider.mjs');const rubric=await loadRubric();const field='impact';const rows=rubric.fields.find(r=>r.field===field).evidenceTypes.map(t=>({type:t.type,evidenceRef:t.type,bytes:'ISOLATED_TEST_ONLY',sha256:sha256('ISOLATED_TEST_ONLY'),recordIdentity:'test',versionIdentity:'1',scope:'isolated-test:model-release:1',observationId:'test',observedAt:at,claimBindings:['test-claim'],kind:'SOURCE_FACT',sourceAuthority:'official',sourceLevel:'official',sourceUrl:'https://example.org/test'}));const request={runId:'ISOLATED_TEST_ONLY',eventKey:'isolated-test:model-release:1',observationId:'test',radar:'AI',sourceFamily:'TEST_ONLY',sourceIdentity:'test',observedAt:at,sourceEvidence:rows.map(r=>({evidenceRef:r.evidenceRef,sha256:r.sha256})),normalizedCandidateFacts:{entity:'isolated-test'},rubricVersion:'1.0',rubricHash:PINS.payload,fieldEvidence:{impact:rows}};
 const timeout=await configureProductionAdapter(path,{fetchImpl:()=>new Promise(()=>{})});assert.equal((await evaluateJudgment(request,field,{rubric,adapter:timeout.adapter,timeoutMs:5})).status,'PROVIDER_ERROR');
 const invalid=await configureProductionAdapter(path,{fetchImpl:async()=>({ok:true,text:async()=>JSON.stringify({stop_reason:'tool_use',content:[{type:'tool_use',name:'submit_judgment',input:{field,value:5,status:'JUDGMENT_READY',provenance:null}}]})})});const r=await evaluateJudgment(request,field,{rubric,adapter:invalid.adapter});assert.equal(r.status,'INVALID_EVIDENCE');assert.equal(r.value,null);const count=invalid.getCalls();assert.equal((await evaluateJudgment({...request,rubricHash:sha256('wrong')},field,{rubric,adapter:invalid.adapter})).status,'INVALID_EVIDENCE');assert.equal(invalid.getCalls(),count);
}));
