import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createContinuousProductionIngestion,decideIngestionRetry} from '../src/lib/radar-production-registry/continuous-ingestion.mjs';
async function fixture(t,options){const root=await mkdtemp(join(tmpdir(),'horizon-retry-boundary-'));t.after(()=>rm(root,{recursive:true,force:true}));return createContinuousProductionIngestion({stateDir:join(root,'radar-v2-prod-identity-dev-claude-code'),...options});}
const response=(body,status=200,header=null)=>({ok:status===200,status,headers:{get:()=>header},text:async()=>body});
for(const [name,body,code] of [['malformed','<?xml version="1.0"?><feed><entry></feed>','MALFORMED_PAYLOAD'],['parser EOF','<feed><entry>','MALFORMED_PAYLOAD'],['empty','','EMPTY_RESPONSE'],['wrong schema','<?xml version="1.0"?><catalog><item/></catalog>','SCHEMA_MISMATCH']])test(`${name}: one attempt, no timer, not F07`,async t=>{let attempts=0,delays=[];const runtime=await fixture(t,{fetchImpl:async()=>{attempts++;return response(body);},sleep:async ms=>delays.push(ms)});await assert.rejects(runtime.fetchFeed(),{code});assert.equal(attempts,1);assert.deepEqual(delays,[]);});
test('5xx uses exactly 1000/2000ms and three attempts',async t=>{let attempts=0,delays=[];const runtime=await fixture(t,{fetchImpl:async()=>{attempts++;return response('',503);},sleep:async ms=>delays.push(ms)});await assert.rejects(runtime.fetchFeed(),{code:'HTTP_SERVER_FAILURE'});assert.equal(attempts,3);assert.deepEqual(delays,[1000,2000]);});
test('explicit body-read mismatch is F07; exact cause code is also supported',async t=>{for(const nested of [false,true]){let attempts=0,delays=[];const runtime=await fixture(t,{fetchImpl:async()=>{attempts++;return { ...response(''),text:async()=>{throw nested?Object.assign(new TypeError('terminated'),{cause:{code:'UND_ERR_RES_CONTENT_LENGTH_MISMATCH'}}):Object.assign(new Error('incomplete response'),{code:'UND_ERR_RES_CONTENT_LENGTH_MISMATCH'});}};},sleep:async ms=>delays.push(ms)});await assert.rejects(runtime.fetchFeed(),{code:'PARTIAL_FETCH'});assert.equal(attempts,3);assert.deepEqual(delays,[1000,2000]);}});
for(const [header,expectedAttempts,expectedDelays] of [['1',3,[1000,1000]],[null,1,[]],['nonsense',1,[]],['31',1,[]]])test(`429 header ${header}: approved honor-or-exhaust boundary`,async t=>{let attempts=0,delays=[];const runtime=await fixture(t,{fetchImpl:async()=>{attempts++;return response('',429,header);},sleep:async ms=>delays.push(ms)});await assert.rejects(runtime.fetchFeed(),{code:'RATE_LIMIT'});assert.equal(attempts,expectedAttempts);assert.deepEqual(delays,expectedDelays);});
for(const method of ['disable','setControl'])test(`${method} during retry stops before next fetch`,async t=>{let calls=0;const runtime=await fixture(t,{fetchImpl:async()=>{calls++;return response('',503);},sleep:async()=>{if(method==='disable')await runtime.disable('KILL_DURING_RETRY');else await runtime.setControl({ingestion:'DISABLED',reason:'DISABLED_DURING_RETRY'});}});await runtime.enable();await assert.rejects(runtime.fetchFeed({requireEnabled:true}),{code:'INGESTION_DISABLED'});assert.equal(calls,1);const audit=await readFile(join(runtime.ingestionDir,'runs',new Date().toISOString().slice(0,10),'fetch-attempts.jsonl'),'utf8');assert.match(audit,/INGESTION_DISABLED/);});
test('retry decision preserves header, rejects deadline overflow and never timers nonretryable',()=>{assert.equal(decideIngestionRetry({failureClass:'RATE_LIMIT',reasonCode:'RATE_LIMIT',retryable:true,retryAfterRaw:'1'},1).retryAfterParsedMs,1000);assert.equal(decideIngestionRetry({failureClass:'RATE_LIMIT',reasonCode:'RATE_LIMIT',retryable:true,retryAfterRaw:'1'},1,{remainingMs:500}).retryDecision,'DO_NOT_RETRY');assert.equal(decideIngestionRetry({failureClass:'MALFORMED_PAYLOAD',reasonCode:'MALFORMED_PAYLOAD',retryable:false},1).delaySource,'NONE');});
