import test from 'node:test';
import assert from 'node:assert/strict';
import {closeRecord,auditedAttempt} from '../src/lib/radar-production-score/boundary.mjs';
const item=()=>({eventKey:'test:version-update:1',observationId:'obs',generated:{status:'RECEIPT_ONLY',receiptOnlyReasons:['MODEL_JUDGMENT_MISSING'],missingRequiredInputs:['impact']},registry:{committed:true,eventKey:'test:version-update:1',observationId:'obs'},security:{scoreEligible:true},human:{status:'UNAVAILABLE'},judgments:[{field:'impact',status:'INSUFFICIENT_EVIDENCE',reasonCodes:['MISSING']}],evidence:{captureSha256:'test-only'},evaluatedAt:'2026-10-05T00:00:00Z'});
test('canonical receipt-only explicitly prevents Score and Action',()=>{const r=closeRecord(item());assert.equal(r.terminalStatus,'RECEIPT_ONLY');assert.equal(r.actionState,'ACTION_NOT_EVALUATED_DUE_TO_SCORE_STATE');assert.equal(r.scoreExecuted,false);assert.equal(r.actionExecuted,false);assert.deepEqual(r.blockingFields,['impact']);assert.equal(r.authorityState.humanValidation,'UNAVAILABLE');assert.deepEqual(closeRecord(item()),r);});
test('unexplained non-ready state rejected',()=>{const i=item();i.generated.receiptOnlyReasons=[];assert.throws(()=>closeRecord(i),/UNEXPLAINED/);});
test('committed identity mismatch rejected',()=>{const i=item();i.registry.eventKey='other';assert.throws(()=>closeRecord(i),/REGISTRY_STATE_REQUIRED/);});
test('ready input cannot bypass unresolved Security Gate',()=>{const i=item();i.generated.status='SCORE_READY';i.security.scoreEligible=false;assert.throws(()=>closeRecord(i),/SECURITY_GATE_BLOCKED/);});
for(const [stage,code] of [['JudgmentProvider timeout','PROVIDER_TIMEOUT'],['JudgmentProvider malformed response','STRUCTURED_RESPONSE_INVALID'],['JudgmentProvider incomplete judgment','DUPLICATE_OR_PARTIAL_PROVIDER_RESULT'],['Human Validation unavailable','HUMAN_VALIDATION_STORE_UNAVAILABLE'],['Score input validation failure','INVALID_SCORE_INPUT'],['Score execution failure','SCORE_EXECUTION_FAILED'],['Action execution failure','ACTION_EXECUTION_FAILED'],['Security Gate rejection','SECURITY_GATE_BLOCKED'],['Registry read failure','REGISTRY_STATE_REQUIRED']])test('isolated bounded failure envelope: '+stage,async()=>{const audit=[];let calls=0;const result=await auditedAttempt(stage,async()=>{calls++;throw Error(code);},{audit,identity:{eventKey:'ISOLATED_TEST_ONLY'},now:()=> '2026-10-05T00:00:00Z'});assert.equal(calls,1);assert.equal(result.ok,false);assert.equal(result.terminalStatus,'RECEIPT_ONLY');assert.equal(result.reasonCode,code);assert.equal(audit.length,1);assert.equal(audit[0].status,'FAILED');assert.equal(audit[0].reasonCode,code);});
