import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomBytes} from 'node:crypto';
import {createIsolatedPublisher,signSynthetic} from '../src/lib/radar-publisher/isolated.mjs';
import {loadFrozenPolicy,evaluateFrozenPolicy} from '../src/lib/radar-publisher/policy.mjs';
import {instruction,sha} from '../src/lib/radar-publisher/canonical.mjs';
const packageDir=path.join(os.homedir(),'.local/state/horizon/policies/publication/1.0.0');
const frozenFacts=JSON.parse(await fs.readFile(new URL('../fixtures/radar-publisher/owner-proof-states-v1.json',import.meta.url))).gateFacts;
const NOW='2026-10-04T04:00:00.000Z',secret=randomBytes(32).toString('hex'),results=[];
async function setup({fault=async()=>{},policyDirectory=packageDir,clock=()=>new Date(NOW)}={}){
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'horizon-publisher-canary-'));
 const pub=await createIsolatedPublisher({root,policyDirectory,secret,now:clock,fault});
 const payload='Synthetic isolated release, never public.';
 const value={domain:'horizon-publication-instruction-v1',eventKey:'synthetic-canary:version-update:1.0',observationIds:['0123456789abcdef'],targetChannel:'review/news',contentSha256:sha(payload)};
 const id=instruction(value).instructionId;
 const scope={policyVersion:'1.0.0',instructionId:id,eventKey:value.eventKey,observationIds:value.observationIds,targetChannel:value.targetChannel,contentSha256:value.contentSha256,reviewSha256:sha('synthetic review'),scoreInputSha256:sha('simulated Score input'),scoreOutputSha256:sha('simulated Score output'),actionOutputSha256:sha('simulated Action output'),securityOutputSha256:sha('simulated Security output')};
 const grant={authorizationId:'SYNTHETIC_TEST_AUTHORIZATION:test-grant',issuerPrincipalId:'synthetic-human',issuedAt:'2026-10-04T03:59:00.000Z',expiresAt:'2026-10-04T04:01:00.000Z',decision:'APPROVE',scope:structuredClone(scope),provenanceSha256:sha('synthetic verified issuer proof'),revocationHistoryRef:'synthetic-revocation-history:empty'};
 const capture={type:'SYNTHETIC_TEST_AUTHORIZATION',body:{namespace:pub.root,instruction:value,currentScope:scope,gateFacts:structuredClone(frozenFacts)}};
 const authorization={type:'SYNTHETIC_TEST_AUTHORIZATION',authorityId:'PROPOSED_EXPLICIT_HUMAN_PUBLICATION_AUTHORIZATION',namespace:pub.root,lookupHealth:'COMPLETE_HEALTHY',complete:true,asOf:NOW,grants:[grant],revokedAuthorizationIds:[]};
 const request={instructionText:JSON.stringify(value),instructionId:id,payload,capture,authorization};
 const resign=()=>{capture.signature=signSynthetic(capture.body,secret);authorization.grantSignature=signSynthetic(authorization.grants[0],secret);authorization.lookupSignature=signSynthetic({grants:authorization.grants,revokedAuthorizationIds:authorization.revokedAuthorizationIds,asOf:authorization.asOf,namespace:authorization.namespace,authorityId:authorization.authorityId,lookupHealth:authorization.lookupHealth,complete:authorization.complete},secret);};resign();
 return {pub,root,request,value,grant,resign};
}
async function run(name,mutate,expected,opts={}){const s=await setup(opts);try{await s.pub.enable();await mutate(s);const r=await s.pub.execute(s.request);assert.equal(r.status,expected);assert.equal((await s.pub.snapshot()).sink.length,expected==='EXECUTED'?1:0);results.push({name,expected,actual:r.status,result:'PASS',receipt:r});return r;}finally{await s.pub.disable();}}
const cases=[
 ['valid authorization',()=>{},'EXECUTED'],
 ['missing authorization',s=>{s.request.authorization=null;},'REJECTED_NOT_AUTHORIZED'],
 ['malformed authorization',s=>{delete s.grant.issuedAt;s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
 ['expired authorization',s=>{s.grant.issuedAt='2026-10-04T03:00:00.000Z';s.grant.expiresAt='2026-10-04T03:59:59.000Z';s.resign();},'REJECTED_AUTHORIZATION_EXPIRED'],
 ['revoked authorization',s=>{s.request.authorization.revokedAuthorizationIds.push(s.grant.authorizationId);s.resign();},'REJECTED_AUTHORIZATION_REVOKED'],
 ...['eventKey','observationIds','instructionId','targetChannel','policyVersion'].map(k=>['wrong '+k,s=>{s.grant.scope[k]=k==='observationIds'?['fedcba9876543210']:'wrong';s.resign();},'REJECTED_AUTHORIZATION_INVALID']),
 ['broken provenance',s=>{s.grant.provenanceSha256='invalid';s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
 ['forged provenance signature',s=>{s.request.authorization.grantSignature=sha('forgery');},'REJECTED_AUTHORIZATION_INVALID'],
 ['wrong authority identity',s=>{s.request.authorization.authorityId='EXPLICIT_HUMAN_VALIDATION';s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
 ['not allowlisted issuer',s=>{s.grant.issuerPrincipalId='model';s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
 ['conflicting grants',s=>{s.request.authorization.grants.push({...s.grant,authorizationId:'SYNTHETIC:other'});s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
 ['incomplete authorization history',s=>{s.request.authorization.complete=false;s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
 ['future issue',s=>{s.grant.issuedAt='2026-10-04T04:00:30.000Z';s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
 ['invalid UTC instant',s=>{s.grant.issuedAt='2026-02-30T03:00:00.000Z';s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
 ['Publisher disabled',s=>s.pub.disable(),'REJECTED_PUBLISHER_DISABLED'],
 ['supplied instruction mismatch',s=>{s.request.instructionId=sha('wrong');},'REJECTED_INSTRUCTION_ID_MISMATCH'],
 ['payload mismatch',s=>{s.request.payload='modified';},'REJECTED_AUTHORIZATION_INVALID'],
 ['receipt-only never authorizes',s=>{s.request.capture.body.gateFacts.scoreInput='RECEIPT_ONLY';s.resign();},'REJECTED_NOT_AUTHORIZED'],
 ['unsigned owner assertions',s=>{s.request.capture.signature=sha('fake');},'REJECTED_AUTHORIZATION_INVALID'],
 ['production-looking Event rejected',s=>{s.value.eventKey='claude-code:version-update:2.1';s.request.capture.body.instruction=s.value;s.request.instructionText=JSON.stringify(s.value);s.request.instructionId=instruction(s.value).instructionId;s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
 ['synthetic marker missing',s=>{s.request.authorization.type='PRODUCTION';},'REJECTED_AUTHORIZATION_INVALID'],
 ['missing healthy lookup',s=>{s.request.authorization.lookupHealth='UNAVAILABLE';s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
 ['scope proof stale',s=>{s.grant.scope.scoreOutputSha256=sha('old score');s.resign();},'REJECTED_AUTHORIZATION_INVALID'],
];
for(const [name,mutate,expected] of cases)test(name,()=>run(name,mutate,expected));
for(const stage of ['sink','partial-sink','audit','idempotency-store','authorization-store'])test(stage+' failure',()=>run(stage+' failure',()=>{},'EXECUTION_FAILED',{fault:async(point,temp)=>{if(point===stage||(stage==='audit'&&point==='failure-audit')){if(temp)await fs.writeFile(temp,'partial');throw Error('INJECTED_'+stage);}}}));
test('policy integrity failures reject, no embedded fallback',async()=>{for(const kind of ['payload','dependency','version','candidate','outer-integrity']){const root=await fs.mkdtemp(path.join(os.tmpdir(),'horizon-publisher-canary-'));const copy=path.join(root,'package');await fs.cp(packageDir,copy,{recursive:true});let file=path.join(copy,kind==='outer-integrity'?'integrity.json':kind==='dependency'?'dependencies/radar-score-policy-v2.1.1.json':'radar-publication-policy-v1.json');await fs.chmod(file,0o600);const obj=JSON.parse(await fs.readFile(file));if(kind==='candidate')obj.status='DRAFT';else if(kind==='version')obj.policyVersion='9.0.0';else obj.corrupted=true;await fs.writeFile(file,JSON.stringify(obj));await run('policy integrity '+kind,()=>{},'REJECTED_POLICY_INTEGRITY',{policyDirectory:copy});}});
test('first, exact replay, escaped slash replay, and kill lifecycle',async()=>{const s=await setup();let r=await s.pub.execute(s.request);assert.equal(r.status,'REJECTED_PUBLISHER_DISABLED');await s.pub.enable();const first=await s.pub.execute(s.request);assert.equal(first.status,'EXECUTED');const replay=await s.pub.execute(s.request);assert.equal(replay.status,'DUPLICATE_EXECUTION');s.request.instructionText=s.request.instructionText.replace('review/news','review\\/news');const equivalent=await s.pub.execute(s.request);assert.equal(equivalent.status,'DUPLICATE_EXECUTION');assert.equal((await s.pub.snapshot()).sink.length,1);await s.pub.disable();r=await s.pub.execute(s.request);assert.equal(r.status,'REJECTED_PUBLISHER_DISABLED');const state=await s.pub.snapshot();for(const row of state.audit.filter(a=>a.attemptId===first.attemptId)){assert.equal(row.instructionId,first.instructionId);assert.equal(row.eventKey,first.eventKey);assert.equal(row.observationId,first.observationId);}results.push({name:'happy path lifecycle and canonical duplicate',result:'PASS',first,replay,equivalent,finalControl:await s.pub.control(),sinkGrowth:[1,0,0],auditIdentityCoverage:100,root:s.root});});
test('concurrent duplicate execution across separate instances',async()=>{const s=await setup();await s.pub.enable();const other=await createIsolatedPublisher({root:s.root,policyDirectory:packageDir,secret,now:()=>new Date(NOW)});const out=await Promise.all(Array.from({length:10},(_,i)=>(i%2?s.pub:other).execute(s.request)));assert.equal(out.filter(r=>r.status==='EXECUTED').length,1);assert.equal(out.filter(r=>r.status==='DUPLICATE_EXECUTION').length,9);assert.equal((await s.pub.snapshot()).sink.length,1);await s.pub.disable();results.push({name:'concurrent duplicate',result:'PASS',executed:1,duplicate:9,sinkRecords:1,root:s.root,receipts:out});});
test('kill during execution before commit cancels sink write',async()=>{let pub;const s=await setup({fault:async p=>{if(p==='before-commit')await pub.kill();}});pub=s.pub;await pub.enable();const r=await pub.execute(s.request);assert.equal(r.status,'REJECTED_PUBLISHER_DISABLED');assert.equal((await pub.snapshot()).sink.length,0);assert.equal((await pub.control()).state,'DISABLED');results.push({name:'kill during execution',expected:'REJECTED_PUBLISHER_DISABLED',actual:r.status,result:'PASS',receipt:r});});
test('corrupted state never succeeds and receipt reports persistence failure',async()=>{const s=await setup();await s.pub.enable();await fs.writeFile(path.join(s.root,'state.json'),'{corrupted');const r=await s.pub.execute(s.request);assert.equal(r.status,'EXECUTION_FAILED');assert.equal(r.persistenceStatus,'NOT_PERSISTED');await s.pub.kill();results.push({name:'corrupted state',result:'PASS',receipt:r});});
test('offline determinism ten captures and replays',async()=>{const vectors=[];for(let i=0;i<10;i++){const s=await setup();await s.pub.enable();const a=await s.pub.execute(s.request),b=await s.pub.execute(s.request);assert.equal(a.status,'EXECUTED');assert.equal(b.status,'DUPLICATE_EXECUTION');vectors.push({instructionId:a.instructionId,authorizationDisposition:a.audit.find(x=>x.operation==='AUTHORIZATION_RESULT').result,first:a.status,replay:b.status,payloadHash:a.payloadHash,idempotencyKey:a.idempotencyKey});await s.pub.disable();}vectors.forEach(v=>assert.deepEqual(v,vectors[0]));results.push({name:'offline determinism 10/10',result:'PASS',identityDelta:0,semanticDispositionDelta:0,vectors});});
test('frozen decision table exact and instructions strict',async()=>{const p=await loadFrozenPolicy(packageDir);const table=p.artifacts['radar-publication-decision-table-v2.json'];for(const row of table.rows)assert.deepEqual(evaluateFrozenPolicy(p,row.evaluated),{disposition:row.disposition,reasonCodes:row.reasonCodes});assert.throws(()=>instruction({...JSON.parse('{}'),domain:'x'}));results.push({name:'frozen table 3856/3856',result:'PASS'});});
test('same content with different observation set cannot republish',async()=>{const s=await setup();await s.pub.enable();assert.equal((await s.pub.execute(s.request)).status,'EXECUTED');s.value.observationIds=['fedcba9876543210'];const id=instruction(s.value).instructionId;s.request.instructionText=JSON.stringify(s.value);s.request.instructionId=id;s.request.capture.body.instruction=s.value;s.request.capture.body.currentScope={...s.grant.scope,observationIds:s.value.observationIds,instructionId:id};s.grant.scope=structuredClone(s.request.capture.body.currentScope);s.resign();const r=await s.pub.execute(s.request);assert.equal(r.status,'REJECTED_AUTHORIZATION_INVALID');assert.equal((await s.pub.snapshot()).sink.length,1);await s.pub.disable();results.push({name:'same content changed observations',result:'PASS',receipt:r,sinkRecords:1});});
test('committed outcome survives response failure and restart',async()=>{let once=true;const s=await setup({fault:async point=>{if(point==='post-commit'&&once){once=false;throw Error('INJECTED_RESPONSE_LOSS');}}});await s.pub.enable();const r=await s.pub.execute(s.request);assert.equal(r.status,'EXECUTION_FAILED');assert.equal(r.commitOutcome,'COMMITTED_RECONCILED');const restarted=await createIsolatedPublisher({root:s.root,policyDirectory:packageDir,secret,now:()=>new Date(NOW)});const replay=await restarted.execute(s.request);assert.equal(replay.status,'DUPLICATE_EXECUTION');assert.equal((await restarted.snapshot()).sink.length,1);await restarted.disable();results.push({name:'committed response failure restart',result:'PASS',failed:r,replay,sinkRecords:1});});
test('redundant identical same-id approvals deduplicate',async()=>run('same authorizationId redundant grant',s=>{s.request.authorization.grants.push(structuredClone(s.grant));s.resign();},'EXECUTED'));
test('equivalent UTC timestamps and exact fractional bounds',async()=>{await run('UTC representations',s=>{s.grant.issuedAt='2026-10-04T03:59:00+00:00';s.request.authorization.asOf='2026-10-04T04:00:00Z';s.resign();},'EXECUTED');await run('submillisecond future issue rejected',s=>{s.grant.issuedAt='2026-10-04T04:00:00.0000001Z';s.resign();},'REJECTED_AUTHORIZATION_INVALID');});
test('closed envelope and raw source enum fail closed',async()=>{await run('unknown gate field',s=>{s.request.capture.body.gateFacts.inventedDefault=true;s.resign();},'REJECTED_NOT_AUTHORIZED');await run('sourceLevel cannot substitute sourceAuthority',s=>{s.request.capture.body.gateFacts.sourceAuthority='research';s.resign();},'REJECTED_NOT_AUTHORIZED');});
test('expiry during execution blocks final commit',async()=>{let current=NOW;await run('expiry during execution',()=>{},'REJECTED_AUTHORIZATION_EXPIRED',{clock:()=>new Date(current),fault:async point=>{if(point==='before-commit')current='2026-10-04T04:02:00.000Z';}});});
test('abandoned execution lock fails closed without stale-lock removal',async()=>{const s=await setup();await s.pub.enable();await fs.writeFile(path.join(s.root,'lock'),'synthetic abandoned owner');const r=await s.pub.execute(s.request);assert.equal(r.status,'EXECUTION_FAILED');assert.equal(r.reason,'ISOLATED_LOCK_UNAVAILABLE');await fs.unlink(path.join(s.root,'lock'));assert.equal((await s.pub.snapshot()).sink.length,0);await s.pub.disable();results.push({name:'abandoned lock',expected:'EXECUTION_FAILED',actual:r.status,result:'PASS',receipt:r});});
test('scope observation set preserves frozen sortedUnique semantics',async()=>run('scope observation set ordering',s=>{s.value.observationIds=['0123456789abcdef','fedcba9876543210'];const id=instruction(s.value).instructionId;s.request.instructionText=JSON.stringify(s.value);s.request.instructionId=id;s.request.capture.body.instruction=s.value;s.request.capture.body.currentScope={...s.grant.scope,instructionId:id,observationIds:s.value.observationIds};s.grant.scope={...structuredClone(s.request.capture.body.currentScope),observationIds:[...s.value.observationIds].reverse()};s.resign();},'EXECUTED'));
for(const segment of ['receipt','idempotency'])test(segment+' partial write failure has no orphan success',async()=>run(segment+' write failure',()=>{},'EXECUTION_FAILED',{fault:async(point,temp)=>{if(point==='partial-sink'){const staged=JSON.parse(await fs.readFile(temp,'utf8'));if(segment==='receipt')staged.receipts.pop();else delete staged.committed[Object.keys(staged.committed)[0]];await fs.writeFile(temp,JSON.stringify(staged));throw Error('INJECTED_'+segment.toUpperCase()+'_WRITE_FAILURE');}}}));
test.after(async()=>{if(process.env.RADAR_PUBLISHER_EVIDENCE)await fs.writeFile(process.env.RADAR_PUBLISHER_EVIDENCE,JSON.stringify({type:'ISOLATED_SYNTHETIC_CANARY',result:'VERIFICATION_EVIDENCE_REQUIRES_SUCCESSFUL_TEST_EXIT',cases:results,caseCount:results.length,productionAuthorizationCreation:0,realPublisherCalls:0,publicPublication:0},null,2)+'\n');});
