import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,sign} from 'node:crypto';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {BootstrapAdmin,canonical,lifecycle,grantProfile} from '../src/lib/radar-bootstrap/index.mjs';
// NON_PRODUCTION_BOOTSTRAP_FAILURE_FIXTURE: ephemeral keys never enter Keychain/artifacts.
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'horizon-bootstrap-test-'));let at='2026-10-06T01:00:00.000Z';const keys=new Map();const factory=ref=>({ref,async create(){if(keys.has(ref))throw Error('KEY_ALREADY_EXISTS');keys.set(ref,generateKeyPairSync('ed25519'));return this.public();},async public(){return keys.get(ref).publicKey.export({type:'spki',format:'der'}).toString('base64');},async sign(bytes){return sign(null,bytes,keys.get(ref).privateKey).toString('base64');}});const admin=new BootstrapAdmin({store:join(dir,'store'),anchor:join(dir,'anchor'),signerFactory:factory,now:()=>at});const pending=await admin.prepareRoot();return {dir,admin,pending,factory,now:v=>at=v,close:()=>rm(dir,{recursive:true,force:true}),activate:()=>admin.activateRoot({confirmation:admin.confirmationInstruction(pending),interactive:true,confirmationRecordId:'NON_PRODUCTION_OPERATOR_FIXTURE'})};}
async function enrolled(f,kind='AUTHOR',suffix='one'){const role=kind==='AUTHOR'?'PROVIDER_QUALIFICATION_FIXTURE_AUTHOR':'HORIZON_RADAR_OWNER';const scope=kind==='AUTHOR'?'PROVIDER_QUALIFICATION_FIXTURE_AUTHORING':'PROVIDER_QUALIFICATION_FIXTURE_APPROVAL';const keyId='test-key:'+suffix,publicKey=await f.factory(keyId).create(),principalId='horizon-principal:'+suffix;const request=await f.admin.issueEnrollmentRequest({principalId,principalType:'CRYPTOGRAPHIC_OPERATOR_PRINCIPAL',displayLabel:null,principalCreatedAt:'2026-10-06T01:00:00.000Z',keyId,publicKey,requestedRoles:[role],requestedScopes:[scope],roleBindings:{[kind==='AUTHOR'?'fixtureAuthorId':'ownerId']:(kind==='AUTHOR'?'horizon-author:':'horizon-owner:')+suffix,principalId},validFrom:'2026-10-06T01:00:00.000Z',validUntil:null});const proof=await f.factory(keyId).sign(Buffer.from(canonical(request)));return {request,proof,result:await f.admin.enrollPrincipal({request,proof})};}
for(const [name,run] of [
 ['candidate-is-not-trusted',async f=>{await assert.rejects(f.admin.load(),/BOOTSTRAP_AUTHORITY_UNAVAILABLE/);assert.equal(f.pending.status,'AWAITING_OPERATOR_CONFIRMATION');}],
 ['same-candidate-resume-no-regeneration',async f=>{assert.deepEqual(await f.admin.prepareRoot(),f.pending);}],
 ['no-unattended-confirmation',async f=>{await assert.rejects(f.admin.activateRoot({confirmation:f.admin.confirmationInstruction(f.pending),interactive:false}),/CONFIRMATION_REQUIRED/);}],
 ['wrong-fingerprint-rejected',async f=>{await assert.rejects(f.admin.activateRoot({confirmation:'wrong',interactive:true,confirmationRecordId:'test'}),/CONFIRMATION_REQUIRED/);}],
 ['valid-external-fixture-confirmation',async f=>{const r=await f.activate();assert.equal(r.state.principals.length,0);assert.equal(r.state.roots[0].scope.includes('SCORE'),false);}],
 ['duplicate-initialization-blocked',async f=>{await f.activate();await assert.rejects(f.admin.prepareRoot(),/ALREADY_INITIALIZED/);}],
 ['author-owner-distinct-enrollment',async f=>{await f.activate();await enrolled(f);await enrolled(f,'OWNER','two');assert.equal((await f.admin.load()).state.principals.length,2);}],
 ['idempotent-enrollment',async f=>{await f.activate();const e=await enrolled(f);const r=await f.admin.enrollPrincipal(e);assert.equal(r.terminal,'IDEMPOTENT_EXISTING_ENROLLMENT');assert.equal(r.receipt.payload.enrollmentId,e.result.receipt.payload.enrollmentId);}],
 ['invalid-request-signature',async f=>{await f.activate();const e=await enrolled(f);await assert.rejects(f.admin.enrollPrincipal({...e,proof:Buffer.alloc(64).toString('base64')}),/AUTHENTICATION_FAILED/);}],
 ['scope-role-mismatch',async f=>{await f.activate();await assert.rejects(f.admin.issueEnrollmentRequest({principalId:'horizon-principal:bad',principalType:'CRYPTOGRAPHIC_OPERATOR_PRINCIPAL',displayLabel:null,principalCreatedAt:'2026-10-06T01:00:00.000Z',keyId:'test-key:bad',publicKey:await f.factory('test-key:bad').create(),requestedRoles:['HORIZON_RADAR_OWNER'],requestedScopes:['SCORE'],roleBindings:{ownerId:'horizon-owner:bad',principalId:'horizon-principal:bad'},validFrom:'2026-10-06T01:00:00.000Z',validUntil:null}),/AUTHORIZATION_FAILED/);}],
 ['root-key-operational-role-leakage',async f=>{await f.activate();const request=await f.admin.issueEnrollmentRequest({principalId:'horizon-principal:bad',principalType:'CRYPTOGRAPHIC_OPERATOR_PRINCIPAL',displayLabel:null,principalCreatedAt:f.pending.createdAt,keyId:f.pending.keyId,publicKey:f.pending.publicKey,requestedRoles:['HORIZON_RADAR_OWNER'],requestedScopes:['PROVIDER_QUALIFICATION_FIXTURE_APPROVAL'],roleBindings:{ownerId:'horizon-owner:bad',principalId:'horizon-principal:bad'},validFrom:f.pending.createdAt,validUntil:null});await assert.rejects(f.admin.enrollPrincipal({request,proof:await f.factory(f.pending.keyId).sign(Buffer.from(canonical(request)))}),/ROOT_OPERATIONAL_ROLE_LEAKAGE/);}],
 ['tampered-pending-candidate',async f=>{const p={...f.pending,publicKeyFingerprint:'0'.repeat(64)};await writeFile(join(f.admin.store,'pending-root.json'),JSON.stringify(p));await assert.rejects(f.admin.prepareRoot(),/BINDING_MISMATCH/);}],
 ['corrupt-registry-fails-closed',async f=>{await f.activate();await writeFile(join(f.admin.store,'current.json'),'bad');await assert.rejects(f.admin.load(),/AUTHORITY_UNAVAILABLE/);}],
 ['anchor-mismatch-fails-closed',async f=>{await f.activate();const path=join(f.admin.anchor,'current.json'),a=JSON.parse(await readFile(path));a.initialFingerprint='0'.repeat(64);await writeFile(path,JSON.stringify(a));await assert.rejects(f.admin.load(),/ANCHOR_MISMATCH/);}],
 ['prepared-journal-not-authority',async f=>{const r=await f.activate();const path=join(f.admin.store,'journals',r.anchor.transactionId+'.json');await writeFile(path,JSON.stringify({transactionId:r.anchor.transactionId,head:r.head,state:'PREPARED'}));await assert.rejects(f.admin.load(),/AUTHORITY_UNAVAILABLE/);}],
 ['principal-normal-rotation',async f=>{await f.activate();const e=await enrolled(f);f.now('2026-10-06T01:01:00.000Z');const keyId='test-key:rotated',pub=await f.factory(keyId).create();await f.admin.governance('rotate-principal-key',{principalId:e.request.principalId,newKeyId:keyId,newPublicKey:pub,newKeyProof:p=>f.factory(keyId).sign(Buffer.from(canonical(p)))});assert.equal((await f.admin.load()).state.principals[0].keys.length,2);}],
 ['root-normal-rotation',async f=>{await f.activate();const keyId='test-root:rotated',pub=await f.factory(keyId).create();f.now('2026-10-06T01:01:00.000Z');await f.admin.governance('rotate-root',{newKeyId:keyId,newPublicKey:pub,newKeyProof:p=>f.factory(keyId).sign(Buffer.from(canonical(p)))});assert.equal((await f.admin.load()).state.roots.length,2);}],
 ['principal-administrative-revocation',async f=>{await f.activate();const e=await enrolled(f);f.now('2026-10-06T01:01:00.000Z');await f.admin.governance('revoke-principal',{principalId:e.request.principalId,principalKeyId:null,reasonCode:'ADMINISTRATIVE_WITHDRAWAL',invalidFrom:null});const p=(await f.admin.load()).state.principals[0];assert.throws(()=>lifecycle(p,'2026-10-06T01:01:00.000Z',{current:true}),/REVOKED/);lifecycle(p,'2026-10-06T01:00:00.000Z');}],
 ['principal-retroactive-key-compromise',async f=>{await f.activate();const e=await enrolled(f);f.now('2026-10-06T01:02:00.000Z');await f.admin.governance('revoke-principal-key',{principalId:e.request.principalId,principalKeyId:e.request.keyId,reasonCode:'COMPROMISE',invalidFrom:'2026-10-06T01:01:00.000Z'});const k=(await f.admin.load()).state.principals[0].keys[0];assert.throws(()=>lifecycle(k,'2026-10-06T01:01:00.000Z'),/REVOKED/);lifecycle(k,'2026-10-06T01:00:00.000Z');}],
 ['manual-recovery-suspends-old-grants',async f=>{await f.activate();await enrolled(f);f.now('2026-10-06T01:02:00.000Z');const keyId='test-root:recovered',pub=await f.factory(keyId).create();const candidate={newBootstrapRootId:'horizon-bootstrap-root:recovered',newKeyId:keyId,newPublicKey:pub,reasonCode:'ROOT_KEY_LOSS',effectiveInvalidFromByKey:{}};const {sha256}=await import('../src/lib/radar-bootstrap/index.mjs');await f.admin.recoverRoot({candidate,confirmation:'CONFIRM RECOVER_ROOT '+candidate.newBootstrapRootId+' '+sha256(Buffer.from(pub,'base64')),interactive:true,confirmationRecordId:'NON_PRODUCTION_RECOVERY'});assert.equal((await f.admin.load()).state.principals[0].status,'SUSPENDED');}]
])test(name,async()=>{const f=await fixture();try{await run(f);}finally{await f.close();}});
test('inclusive-key-window-and-expired-failure',()=>{const a={validFrom:'2026-10-06T00:00:00.000Z',validUntil:'2026-10-06T01:00:00.000Z',status:'RETIRED',revokedAt:null,invalidFrom:null};lifecycle(a,a.validFrom);lifecycle(a,a.validUntil);assert.throws(()=>lifecycle(a,'2026-10-06T01:00:00.001Z'),/EXPIRED/);});
