import test from 'node:test';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';import {writeFile} from 'node:fs/promises';
import {QualificationTiming,observeFetch,instrumentAdapter} from '../src/lib/radar-qualification/timing.mjs';
const fake={stop_reason:'tool_use',content:[{type:'tool_use',name:'submit_judgment',input:{value:1}}],model:'fixture'};
async function scenario(mode,timing){
 const c=new AbortController();let timer;const fetchImpl=async(_,options)=>{
 assert.equal(options.signal,c.signal);
 if(mode==='transport')throw TypeError('ISOLATED_TRANSPORT');
 if(mode==='timeout'||mode==='abort')return new Promise((_,reject)=>options.signal.addEventListener('abort',()=>reject(Error('ISOLATED_ABORT')),{once:true}));
 if(mode==='body-timeout')return {status:200,ok:true,text:()=>new Promise((_,reject)=>options.signal.addEventListener('abort',()=>reject(Error('ISOLATED_ABORT')),{once:true}))};
 if(mode==='observer')return {status:200,ok:true,text:async()=>{throw Error('ISOLATED_BODY_FAILURE');}};
 return new Response(mode==='schema'?'broken-json':JSON.stringify(fake));};
 const observer=observeFetch(fetchImpl,{timing});const provider={adapter:{async execute(_,options){const response=await observer.fetch('https://fixture.invalid',{signal:options.signal,body:'{}'});if(!response.ok)throw Error('HTTP');let raw;try{raw=JSON.parse(await response.text());}catch(e){if(c.signal.aborted)throw e;throw Error('SCHEMA');}return raw;}}};instrumentAdapter(provider,timing);
 try{return await Promise.race([provider.adapter.execute({}, {signal:c.signal}),new Promise((_,reject)=>{timer=setTimeout(()=>{timing?.mark('Q21');timing?.mark('Q22');c.abort();reject(Error('PROVIDER_TIMEOUT'));},20);})]).then(()=> 'VALID',e=>e.message==='PROVIDER_TIMEOUT'?'PROVIDER_TIMEOUT':c.signal.aborted?'PROVIDER_TIMEOUT':e.code==='QUALIFICATION_AUDIT_FAILURE'?'QUALIFICATION_AUDIT_FAILURE':e.message==='SCHEMA'?'SCHEMA':'TRANSPORT');}finally{clearTimeout(timer);timing?.mark('Q25');}
}
for(const mode of ['success','timeout','body-timeout','transport','schema','abort','observer'])test('timing terminal EXACT MATCH '+mode,async()=>{assert.equal(await scenario(mode,new QualificationTiming()),await scenario(mode,null));});
test('sink failure closed before outbound; existing audit failure class',()=>{const t=new QualificationTiming({sink(){throw Error('sink');}});t.mark('Q0');assert.throws(()=>t.assertReady(),{code:'QUALIFICATION_AUDIT_FAILURE'});});
test('headers before body, one text consumption, no clone',async()=>{let release,count=0;const t=new QualificationTiming();const o=observeFetch(async()=>({status:200,ok:true,text:()=>{count++;return new Promise(resolve=>release=resolve);},clone(){throw Error('NO_CLONE');}}),{timing:t});const r=await o.fetch('https://fixture.invalid',{body:'{}'});assert(o.observed[0].headersReceived);assert(!o.observed[0].bodyComplete);const reading=r.text();release(JSON.stringify(fake));await reading;assert.equal(count,1);assert.equal(o.observed[0].modelId,'fixture');});
test('secret metadata rejected',()=>{const t=new QualificationTiming();t.mark('Q8','POINT',{apiKey:'SECRET_SENTINEL',authorization:'SECRET_SENTINEL',errorMessage:'SECRET_SENTINEL',bytes:3});assert(!JSON.stringify(t.snapshot()).includes('SECRET_SENTINEL'));});
test('monotonic clocks and native hooks',()=>{let tick=0;const t=new QualificationTiming({clock:()=>++tick});t.mark('Q5','START');t.mark('Q5','END');assert.equal(t.snapshot().stages.find(s=>s.stage==='Q5').durationMs,1);t.attachTransport();assert.equal(t.subscriptions.length,9);t.close();});
test('synthetic overhead',async()=>{const deltas=[];for(let i=0;i<100;i++){const a=performance.now();await scenario('success',null);const bare=performance.now()-a;const b=performance.now();await scenario('success',new QualificationTiming());deltas.push(performance.now()-b-bare);}deltas.sort((a,b)=>a-b);const report={providerCalls:0,iterations:100,medianOverheadMs:deltas[50],maximumObservedOverheadMs:Math.max(...deltas),method:'Paired synthetic in-process, raw deltas; no network or timeout subtraction',rawDeltasMs:deltas};await writeFile('/private/tmp/phase92-timing-resume/overhead.json',JSON.stringify(report,null,2));assert(report.maximumObservedOverheadMs<50);});
test('old full-clone observer vs new single read: payload and terminal equivalence',async()=>{
 const {configureProductionAdapter}=await import('../src/lib/radar-judgment/production-adapter.mjs');const {mkdtemp,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const {join}=await import('node:path');
 const dir=await mkdtemp(join(tmpdir(),'timing-equivalence-')),config=join(dir,'config.json');await writeFile(config,JSON.stringify({agents:{defaults:{model:{primary:'FAKE/MODEL'}}},models:{providers:{FAKE:{api:'anthropic-messages',apiKey:'FAKE_NOT_A_CREDENTIAL',baseUrl:'https://fixture.invalid/v1',models:[{id:'MODEL'}]}}}}));
 try{for(const mode of ['success','invalid','http']){const sent=[];let consumed=0;const fetchImpl=async(url,options)=>{sent.push({url,method:options.method,redirect:options.redirect,headers:options.headers,body:options.body});const r=new Response(mode==='invalid'?'invalid':JSON.stringify(fake),{status:mode==='http'?500:200});const text=r.text.bind(r);r.text=()=>{consumed++;return text();};return r;};
 const old=async(url,options)=>{const r=await fetchImpl(url,options);const text=await r.clone().text();try{JSON.parse(text);}catch{}return r;};const newer=observeFetch(fetchImpl,{timing:new QualificationTiming()});const outcomes=[];
 for(const f of [old,newer.fetch]){const p=await configureProductionAdapter(config,{fetchImpl:f});try{outcomes.push(JSON.stringify(await p.adapter.execute({test:'payload'},{signal:new AbortController().signal,requestFingerprint:'hash'})));}catch(e){outcomes.push(e.message);}}
 assert.equal(outcomes[0],outcomes[1]);assert.deepEqual(sent[0],sent[1]);assert.equal(consumed,mode==='http'?1:2); // new path always one read; legacy HTTP-error path reads clone only.
 }}finally{await rm(dir,{recursive:true,force:true});}
});
