import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,sign}from'node:crypto';import {readFile,writeFile}from'node:fs/promises';
import {canonical}from'../src/lib/radar-judgment/provider.mjs';import {hashValidation}from'../src/lib/radar-judgment/human.mjs';import {verifyIdentityAt,verifyHumanEnvelope,lookupAuthenticatedHuman}from'../src/lib/radar-capability/authentication.mjs';import {domainDecision,zeroJudgmentState,compareStructuredReference,domainMechanismReadiness}from'../src/lib/radar-capability/domain.mjs';
const tag='NON_PRODUCTION_TEST',at='2026-10-06T00:00:00Z',before='2026-10-01T00:00:00Z',after='2026-10-07T00:00:00Z';
function fixture(){const keys=generateKeyPairSync('ed25519'),scope={validatedVersion:'test',validatedCapabilities:['test'],validatedUsage:tag,validatedEnvironment:tag},pub=keys.publicKey.export({format:'der',type:'spki'}).toString('base64');const trust={healthy:true,complete:true,ownerAuthenticated:true,validators:[{validatorId:tag,status:'ACTIVE',validFrom:before,validUntil:after,revokedAt:null,allowedScopes:[scope]}],keys:[{validatorId:tag,keyId:'test-key',publicKey:pub,algorithm:'Ed25519',status:'ACTIVE',validFrom:before,validUntil:after,revokedAt:null,invalidFrom:null,revocationReason:null}]};const record={validationId:'test-validation',eventKey:'test:release:initial',observationId:'test-observation',eventScopeAuthorized:false,entity:'test',recordVersion:'1',status:'ACTIVE',validatedBy:tag,validatorAuthorityRef:tag,validationType:'ENTITY_LEVEL',validatedAt:at,scope,evidenceRefs:['test-evidence'],provenance:{authority:'EXPLICIT_HUMAN_VALIDATION',method:'AUTHENTICATED_HUMAN',authenticationRef:'test-signature'},recordHash:''};record.recordHash=hashValidation(record);const payload={schemaVersion:1,validationId:record.validationId,validatorId:tag,recordHash:record.recordHash,eventKey:record.eventKey,observationId:record.observationId,validationScope:scope,rubricId:'SCORE_INPUT_RUBRIC_1.0',rubricVersion:'1.0',attestedFields:['ENTITY_LEVEL'],evidenceReferences:record.evidenceRefs,createdAt:at,keyId:'test-key',signedAt:at};const signed={record,payload,signature:sign(null,Buffer.from(canonical(payload)),keys.privateKey).toString('base64')};return {trust,signed,keys,query:{eventKey:record.eventKey,observationId:record.observationId,entity:'test',scope},identity:{validatorId:tag,keyId:'test-key',signedAt:at,scope}};}
const cases=[['unknown-validator',f=>f.identity.validatorId='unknown','AUTHORITY_UNAVAILABLE'],['unknown-key',f=>f.identity.keyId='unknown','AUTHORITY_UNAVAILABLE'],['scope-mismatch',f=>f.identity.scope={x:'other'},'NOT_FOUND'],['before-validity',f=>f.identity.signedAt='2026-09-30T00:00:00Z','NOT_FOUND'],['after-validity',f=>f.identity.signedAt='2026-10-08T00:00:00Z','NOT_FOUND'],['normal-rotation-historical',f=>{f.trust.keys[0].status='RETIRED';f.trust.keys.push({...f.trust.keys[0],keyId:'new-key',publicKey:generateKeyPairSync('ed25519').publicKey.export({format:'der',type:'spki'}).toString('base64'),status:'ACTIVE'});},'AUTHORIZED'],['key-revocation-after-signed',f=>{Object.assign(f.trust.keys[0],{status:'REVOKED',revokedAt:after});},'AUTHORIZED'],['key-revocation-at-signed',f=>Object.assign(f.trust.keys[0],{status:'REVOKED',revokedAt:at}),'NOT_FOUND'],['retroactive-compromise',f=>Object.assign(f.trust.keys[0],{status:'REVOKED',revokedAt:after,invalidFrom:before,revocationReason:'COMPROMISE'}),'NOT_FOUND'],['validator-revocation',f=>Object.assign(f.trust.validators[0],{status:'REVOKED',revokedAt:at}),'NOT_FOUND'],['trust-unavailable',f=>f.trust.healthy=false,'AUTHORITY_UNAVAILABLE'],['trust-corrupt',f=>f.trust.keys.push({...f.trust.keys[0]}),'AUTHORITY_UNAVAILABLE']];
for(const [name,mutate,expected]of cases)test(tag+' identity '+name,()=>{const f=fixture();mutate(f);assert.equal(verifyIdentityAt(f.identity,f.trust).status,expected);});
for(const [name,mutate,expected]of [['valid',()=>{},'VERIFIED'],['invalid-signature',f=>f.signed.signature='invalid','AUTHORITY_UNAVAILABLE'],['payload-tamper',f=>f.signed.payload.eventKey='tampered','AUTHORITY_UNAVAILABLE'],['record-hash',f=>f.signed.record.recordHash='0'.repeat(64),'AUTHORITY_UNAVAILABLE'],['rubric-mismatch',f=>{f.signed.payload.rubricVersion='other';f.signed.signature=sign(null,Buffer.from(canonical(f.signed.payload)),f.keys.privateKey).toString('base64');},'NOT_FOUND']])test(tag+' envelope '+name,()=>{const f=fixture();mutate(f);assert.equal(verifyHumanEnvelope(f.signed,f.trust).status,expected);});
for(const mode of ['found','empty','unavailable','corrupt','duplicate','trust-verification-failure'])test(tag+' lookup '+mode,async()=>{const f=fixture(),snapshot={healthy:true,complete:true,records:mode==='empty'?[]:mode==='duplicate'?[f.signed,f.signed]:[f.signed]};const ports={trustPort:{load:async()=>f.trust,verifySnapshot:async()=>mode!=='trust-verification-failure'},storePort:{load:async()=>{if(mode==='unavailable')throw Error('isolated');return snapshot;},verifySnapshot:async()=>mode!=='corrupt'}};assert.equal((await lookupAuthenticatedHuman(f.query,ports)).status,mode==='found'?'FOUND':mode==='empty'?'NOT_FOUND':'AUTHORITY_UNAVAILABLE');});
test('production ports never default to empty healthy authority',async()=>assert.equal((await lookupAuthenticatedHuman({})).status,'AUTHORITY_UNAVAILABLE'));
const S='/Users/qiuwenbo/.local/state/horizon';const rules=JSON.parse(await readFile(S+'/radar-judgment-domain-quality-decision-matrix-v1.json')).rulesInPrecedenceOrder;const fixtures=JSON.parse(await readFile(S+'/radar-judgment-domain-quality-boundary-fixtures-v1.json')).fixtures;
for(const f of fixtures)test(tag+' domain frozen boundary '+f.id,()=>assert.equal(domainDecision(f.predicates,rules).status,f.expected));
test('zero judgment frozen Provider dependency remains blocked',()=>assert.equal(zeroJudgmentState({realJudgments:0,mechanismReady:true,providerReady:false,populationComplete:true}).status,'BLOCKED_REVIEW_AUTHORITY_UNAVAILABLE'));
test('zero judgment all approved prerequisites permits N/A, never PASS',()=>assert.equal(zeroJudgmentState({realJudgments:0,mechanismReady:true,providerReady:true,populationComplete:true}).status,'NOT_APPLICABLE_NO_REAL_JUDGMENT'));
function reference(){return Object.fromEntries(['impact','actionability','confidence','novelty'].map(field=>[field,{field,status:'JUDGMENT_READY',value:1,reasonCodes:['test'],conflictEvidenceRefs:[],assessments:[{predicateId:'test',state:'TRUE'}]}]));}
for(const mode of ['exact','numeric','reason','predicate','incomplete'])test(tag+' domain comparator '+mode,()=>{const j=reference(),r=reference();if(mode==='numeric')r.impact.value=2;if(mode==='reason')r.impact.reasonCodes=['other'];if(mode==='predicate')r.impact.assessments[0].state='FALSE';if(mode==='incomplete')delete r.novelty;assert.equal(compareStructuredReference(j,r).status,mode==='exact'?'PASS':mode==='incomplete'?'INSUFFICIENT_EVIDENCE':'FAIL');});
test('component-only code does not qualify production Domain mechanism',()=>assert.equal(domainMechanismReadiness({authorityReady:false,eligibilityReady:false,bindingReady:false,proofValidationReady:false,historyReady:false,auditReady:false}).status,'BLOCKED'));

test('Human technical validation cannot grant numeric rubric attestation',()=>{const f=fixture();f.signed.payload.attestedFields=['impact'];f.signed.signature=sign(null,Buffer.from(canonical(f.signed.payload)),f.keys.privateKey).toString('base64');assert.equal(verifyHumanEnvelope(f.signed,f.trust).status,'NOT_FOUND');});
test('conflicting independently signed row in same validation version fails closed',async()=>{const f=fixture(),other=structuredClone(f.signed);other.record.status='STALE';other.record.recordHash=hashValidation(other.record);other.payload.recordHash=other.record.recordHash;other.signature=sign(null,Buffer.from(canonical(other.payload)),f.keys.privateKey).toString('base64');const ports={trustPort:{load:async()=>f.trust,verifySnapshot:async()=>true},storePort:{load:async()=>({healthy:true,complete:true,records:[f.signed,other]}),verifySnapshot:async()=>true}};assert.equal((await lookupAuthenticatedHuman(f.query,ports)).status,'AUTHORITY_UNAVAILABLE');});

test('algorithm label cannot authenticate a non-Ed25519 public key',()=>{const f=fixture(),ec=generateKeyPairSync('ec',{namedCurve:'prime256v1'});f.trust.keys[0].publicKey=ec.publicKey.export({format:'der',type:'spki'}).toString('base64');f.signed.signature=sign('sha256',Buffer.from(canonical(f.signed.payload)),ec.privateKey).toString('base64');assert.equal(verifyHumanEnvelope(f.signed,f.trust).status,'AUTHORITY_UNAVAILABLE');});

test('frozen capability-set equality is insensitive to array ordering',()=>{const f=fixture();f.trust.validators[0].allowedScopes=[{...f.identity.scope,validatedCapabilities:['b','a']}];f.identity.scope={...f.identity.scope,validatedCapabilities:['a','b']};assert.equal(verifyIdentityAt(f.identity,f.trust).status,'AUTHORIZED');});
