import {test}from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import {BootstrapAdmin}from'../src/lib/radar-bootstrap/index.mjs';import{loadAdministrationPolicies,AdministrationStore,verifyAdminAction,businessEligibility,validateBusinessTransition}from'../src/lib/radar-capability/administration.mjs';
const S='/Users/qiuwenbo/.local/state/horizon',T='/private/tmp/phase92-admin-resume-v2',policies=await loadAdministrationPolicies(S),bootstrap=new BootstrapAdmin(),root=(await bootstrap.load()).state;
for(const kind of ['human','domain']){const b=JSON.parse(await readFile(T+'/'+kind+'-business.json')),admin=JSON.parse(await readFile(S+'/administration-runtime-v2/'+kind+'Admin.json'));const store=new AdministrationStore({path:S+'/administration-runtime-v2/'+kind+'-isolated-trust',anchor:'/Users/qiuwenbo/.local/share/horizon-authority-anchors/administration-v2/'+kind+'-isolated-trust',bootstrap,policies}),snapshot=await store.load(),q={principalId:b.subjectPrincipalId,keyId:b.subjectKeyId,role:kind==='human'?'HUMAN_VALIDATOR':'DOMAIN_REVIEWER',alias:b.alias,scope:b.scope,at:b.grant.payload.signedAt,current:false};
 test(kind+' actual authenticated DAG chain loads',()=>{for(const original of [b.enrollment,b.registration,b.grant])assert.deepEqual(snapshot.records.find(r=>r.payload.operationId===original.payload.operationId),original);assert.equal(businessEligibility(snapshot,q).status,'ELIGIBLE');});
 test(kind+' historical actual grant authentication',()=>assert.equal(verifyAdminAction(b.grant,{rootState:root,policies,acceptedAt:new Date().toISOString()}).admin.principalId,admin.principalId));
 for(const [label,mutate]of [['missing Root identity',x=>x.rootState.principals=x.rootState.principals.filter(p=>p.principalId!==q.principalId)],['revoked Root principal',x=>{const p=x.rootState.principals.find(p=>p.principalId===q.principalId);p.status='REVOKED';p.revokedAt=q.at;}],['revoked Root key',x=>{const k=x.rootState.principals.find(p=>p.principalId===q.principalId).keys[0];k.status='REVOKED';k.revokedAt=q.at;}],['missing grant',x=>x.records=x.records.filter(r=>!r.payload.grantId)],['wrong key',x=>{}],['corrupt completeness',x=>x.complete=false]])test(kind+' rejects '+label,()=>{const x=structuredClone(snapshot);mutate(x);const query=label==='wrong key'?{...q,keyId:'horizon-principal-key:unknown'}:q;assert.notEqual(businessEligibility(x,query).status,'ELIGIBLE');});
 for(const [label,mutate]of [['wrong signature',x=>x.signature='AAAA'],['scope mismatch',x=>x.payload.scope=[]],['payload tamper',x=>x.payload.targetIdentity='wrong'],['wrong admin',x=>x.payload.adminPrincipalId=q.principalId],['missing field',x=>delete x.payload.signedAt]])test(kind+' rejects action '+label,()=>{const x=structuredClone(b.grant);mutate(x);assert.throws(()=>verifyAdminAction(x,{rootState:root,policies,acceptedAt:new Date().toISOString()}));});
 test(kind+' Root identity cannot substitute business enrollment',()=>{const x={...snapshot,records:[]};assert.equal(businessEligibility(x,q).status,'NOT_ELIGIBLE');});
 test(kind+' registration PoP exact binding validates',()=>validateBusinessTransition(b.registration,[b.enrollment],root,policies,{historical:true}));
 test(kind+' unregistered grant blocked',()=>assert.throws(()=>validateBusinessTransition(b.grant,[b.enrollment],root,policies,{historical:true})));
 test(kind+' audit signature tamper blocks bundle',async()=>{const x=structuredClone(snapshot.bundle);x.audit.signature='AAAA';await assert.rejects(store.verifyBundle(x,root));});
 test(kind+' committed state records tamper blocks bundle',async()=>{const x=structuredClone(snapshot.bundle);x.state.records=[];await assert.rejects(store.verifyBundle(x,root));});
}

for(const [label,profile,actionType]of [["human","HUMAN_TRUST_COMMIT_1.0","HUMAN_TRUST_COMMIT"],["domain","DOMAIN_TRUST_COMMIT_1.0","DOMAIN_TRUST_COMMIT"]])test(label+" unregistered standalone commit profile fails closed",()=>assert.throws(()=>verifyAdminAction({payload:{profile,actionType},canonicalPayloadHash:"0".repeat(64),signature:"AAAA"},{rootState:root,policies,acceptedAt:new Date().toISOString()}),/ADMIN_GRANT_AUTHORITY_MISMATCH/));
