import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {BootstrapAdmin} from '../src/lib/radar-bootstrap/index.mjs';import {AdministrationStore,loadAdministrationPolicies,businessEligibility} from '../src/lib/radar-capability/administration.mjs';import {HumanValidationStore,verifyHumanEntry} from '../src/lib/radar-capability/human-store.mjs';import {loadSnapshotProfile,digest,compareEntries,snapshotIdentity,verifySnapshotContent,same} from '../src/lib/radar-capability/snapshot-profile.mjs';
const S='/Users/qiuwenbo/.local/state/horizon',T='/private/tmp/phase92-snapshot-resume',bootstrap=new BootstrapAdmin(),policies=await loadAdministrationPolicies(S),profile=await loadSnapshotProfile(S),admin=new AdministrationStore({path:S+'/administration-runtime-v2/human-isolated-trust',anchor:'/Users/qiuwenbo/.local/share/horizon-authority-anchors/administration-v2/human-isolated-trust',bootstrap,policies}),store=new HumanValidationStore({path:S+'/administration-runtime-v2/human-isolated-validation',anchor:'/Users/qiuwenbo/.local/share/horizon-authority-anchors/administration-v2/human-isolated-validation',administration:admin,profile}),snapshot=await store.load(),state=await admin.load(),entry=snapshot.records[0];
test('actual signed snapshot current chain and audit validate',async()=>assert.equal((await store.load()).terminal,'SNAPSHOT_VERIFIED'));
test('actual entries independently verify including historical lifecycle rows',()=>snapshot.records.forEach(e=>verifyHumanEntry(e,state)));
test('constructor source order canonical equivalence',()=>assert.equal(digest([...snapshot.records].sort(compareEntries)),digest([...snapshot.records].reverse().sort(compareEntries))));
test('recursive object insertion order canonical equivalence',()=>assert.equal(digest({b:{z:2,a:1},a:3}),digest({a:3,b:{a:1,z:2}})));
test('wire reordering rejected',()=>{const content=structuredClone(snapshot.package.content);content.entries.reverse();assert.throws(()=>verifySnapshotContent(content,profile));});
test('same identity payload stable',()=>assert.equal(snapshotIdentity(snapshot.package.action.payload,profile),snapshot.package.action.payload.snapshotId));
for(const key of profile.constraintPayload.objectDefinition.identityPayloadKeys)test('identity binds '+key,()=>{const payload=structuredClone(snapshot.package.action.payload);payload[key]=payload[key]===null?'changed':String(payload[key])+'changed';assert.notEqual(snapshotIdentity(payload,profile),snapshot.package.action.payload.snapshotId);});
test('new later same-key grant preserves historical bound original grant',()=>{const x=structuredClone(state),old=x.records.find(r=>r.payload.grantId===entry.validatorGrantId),later=structuredClone(old);later.payload.signedAt='2099-01-01T00:00:00.000Z';later.payload.validFrom=later.payload.signedAt;later.payload.grantId='future-grant';x.records.push(later);verifyHumanEntry(entry,x);const q={principalId:entry.validatorPrincipalId,keyId:entry.payload.keyId,role:'HUMAN_VALIDATOR',alias:entry.payload.validatorId,scope:entry.record.scope,at:entry.payload.signedAt,current:false};assert.equal(businessEligibility(x,q).grant.grantId,entry.validatorGrantId);});
const corruptions=[['record omission',p=>p.content.entries.pop()],['record addition',p=>p.content.entries.push(entry)],['record hash',p=>p.content.entries[0].record.recordHash='0'.repeat(64)],['validator identity',p=>p.content.entries[0].validatorPrincipalId='wrong'],['validator key',p=>p.content.entries[0].payload.keyId='wrong'],['grant hash',p=>p.content.entries[0].validatorGrantHash='0'.repeat(64)],['rubric',p=>p.content.entries[0].payload.rubricVersion='wrong'],['scope',p=>p.content.entries[0].payload.validationScope.validatedUsage='wrong'],['content hash',p=>p.action.payload.contentHash='0'.repeat(64)],['store',p=>p.action.payload.storeId='wrong'],['environment',p=>p.action.payload.environment='PRODUCTION'],['profile',p=>p.action.payload.profile='wrong'],['Admin signer',p=>p.action.payload.adminPrincipalId='wrong'],['Admin key',p=>p.action.payload.adminKeyId='wrong'],['signature',p=>p.action.signature='AAAA'],['predecessor identity',p=>p.action.payload.previousSnapshotId='wrong'],['predecessor hash',p=>p.action.payload.previousSnapshotHash='0'.repeat(64)]];
for(const [label,mutate]of corruptions)test('reject '+label,async()=>{const p=structuredClone(snapshot.package);mutate(p);await assert.rejects(store.verifyPackage(p));});
for(const field of ['storeAnchorHash','receiptHash','auditHash','committedHeadHash','stateHash','transactionId'])test('reject commitProof '+field,async()=>{const p=structuredClone(snapshot.package);p.commitProof[field]='0'.repeat(64);await assert.rejects(store.verifyPackage(p));});
test('historical snapshot uses retained census',async()=>{const evidence=JSON.parse(await fs.readFile(T+'/human-base.json'));assert.equal((await store.load({historicalId:evidence.empty})).records.length,0);assert.equal((await store.load({historicalId:evidence.one})).records.length,1);});
test('snapshot action cannot standalone commit Admin without Store transaction',async()=>assert.rejects(admin.commit(snapshot.package.action),/SNAPSHOT_ATOMICITY_CONFORMANCE_FAILURE/));
// Replay exact already-signed staged bytes; no keys or new signing in recovery tests.
async function preparedClone(name,mutate){const base=T+'/fault-before-committed',d=await fs.mkdtemp('/private/tmp/horizon-snapshot-recovery-');for(const n of ['store','anchor','admin','admin-anchor'])await fs.cp(base+'/'+n,d+'/'+n,{recursive:true});const a=JSON.parse(await fs.readFile(d+'/anchor/current.json')),jPath=d+'/store/transactions/'+a.transactionId+'.json',j=JSON.parse(await fs.readFile(jPath)),prior=JSON.parse(await fs.readFile(d+'/store/anchors/'+j.previousAnchorHash+'.json')),oldPointer=JSON.parse(await fs.readFile(d+'/admin/'+j.previousAdministrationHeadHash+'.head.json'));j.state='PREPARED';await fs.writeFile(jPath,JSON.stringify(j));await fs.writeFile(d+'/admin/transactions/'+j.transactionId+'.journal.json',JSON.stringify({state:'PREPARED',head:j.targetAdministrationHeadHash}));for(const p of [d+'/store/current.json',d+'/anchor/current.json'])await fs.writeFile(p,JSON.stringify(prior));for(const p of [d+'/admin/current.json',d+'/admin-anchor/current.json'])await fs.writeFile(p,JSON.stringify(oldPointer));const pkgPath=d+'/store/snapshots/'+digest(j.snapshotId)+'.json',pkg=JSON.parse(await fs.readFile(pkgPath));await mutate?.({pkg,j,anchor:a,prior,d,pkgPath,jPath});const ad=new AdministrationStore({path:d+'/admin',anchor:d+'/admin-anchor',bootstrap,policies}),st=new HumanValidationStore({path:d+'/store',anchor:d+'/anchor',administration:ad,profile});return {st,d,j,prior,oldPointer};}
for(const field of ['receiptHash','auditHash','stateHash','storeAnchorHash','committedHeadHash','transactionId'])test('recovery rejects corrupt staged proof before commit '+field,async()=>{const f=await preparedClone(field,async({pkg,pkgPath})=>{pkg.commitProof[field]='0'.repeat(64);await fs.writeFile(pkgPath,JSON.stringify(pkg));});await assert.rejects(f.st.recover());assert.equal(JSON.parse(await fs.readFile(f.d+'/store/transactions/'+f.j.transactionId+'.json')).state,'PREPARED');assert(same(JSON.parse(await fs.readFile(f.d+'/anchor/current.json')),f.prior));assert(same(JSON.parse(await fs.readFile(f.d+'/admin-anchor/current.json')),f.oldPointer));});
test('recovery rejects staged anchor/action mismatch before commit',async()=>{const f=await preparedClone('anchor',async({anchor,d,j})=>{anchor.snapshotHash='0'.repeat(64);await fs.writeFile(d+'/store/anchors/'+j.targetAnchorHash+'.json',JSON.stringify(anchor));});await assert.rejects(f.st.recover());assert.equal(JSON.parse(await fs.readFile(f.d+'/store/transactions/'+f.j.transactionId+'.json')).state,'PREPARED');});
test('recovery rejects predecessor journal mismatch before commit',async()=>{const f=await preparedClone('predecessor',async({j,jPath})=>{j.previousAdministrationHeadHash='0'.repeat(64);await fs.writeFile(jPath,JSON.stringify(j));});await assert.rejects(f.st.recover());assert.equal(JSON.parse(await fs.readFile(f.d+'/store/transactions/'+f.j.transactionId+'.json')).state,'PREPARED');});
test('recovery completes exact staged bytes and repeats without signing',async()=>{const f=await preparedClone('healthy');const a=await f.st.recover();assert.equal(a.terminal,'SNAPSHOT_VERIFIED');const b=await f.st.recover();assert.equal(b.terminal,'SNAPSHOT_VERIFIED');assert(same(a.package,b.package));});
