import {readFile,mkdir,open,rename,unlink,lstat} from 'node:fs/promises';
import {join,resolve} from 'node:path';import {randomUUID} from 'node:crypto';
import {canonical,sha256} from '../radar-judgment/provider.mjs';
import {loadSnapshotProfile,verifySnapshotActionFields} from './snapshot-profile.mjs';
import {loadDomainSnapshotProfile,verifyDomainActionFields} from './domain-snapshot-profile.mjs';
import {exact,time,lifecycle,signatureValid,fail} from '../radar-bootstrap/index.mjs';
const equal=(a,b)=>canonical(a)===canonical(b),digest=x=>sha256(canonical(x));
export async function loadAdministrationPolicies(path){
 const names=['radar-human-validation-admin-role-v1.json','radar-domain-review-admin-role-v1.json','radar-human-validator-grant-v1.json','radar-domain-reviewer-grant-v1.json','radar-human-validator-revocation-v1.json','radar-domain-reviewer-revocation-v1.json','radar-domain-reference-authority-v1.json'];
 const files=await Promise.all(names.map(async n=>JSON.parse(await readFile(join(path,n))))),profiles={};
 for(const f of files){if(f.signedOperationProfiles)for(const [p,v]of Object.entries(f.signedOperationProfiles))profiles[p]=v;else profiles[f.profile]=f;}
 for(const [type,keys]of Object.entries(files[6].metadataTransitionFields))profiles[files[6].metadataTransitionProfiles[type]]={payloadRequiredFields:keys};
 let snapshotProfile,domainSnapshotProfile;try{snapshotProfile=await loadSnapshotProfile(path);}catch(e){if(e.code!=='ENOENT')throw e;}if(snapshotProfile)profiles[snapshotProfile.wireProfile]={payloadRequiredFields:snapshotProfile.constraintPayload.objectDefinition.signedPayloadRequiredFields};try{domainSnapshotProfile=await loadDomainSnapshotProfile(path);}catch(e){if(e.code!=='ENOENT')throw e;}if(domainSnapshotProfile)profiles[domainSnapshotProfile.wireProfile]={payloadRequiredFields:domainSnapshotProfile.constraintPayload.definitions.object.signedPayloadRequiredFields};return {human:files[0],domain:files[1],profiles,snapshotProfile,domainSnapshotProfile};
}
export function authorizeAdminPayload(p,{rootState,policies,acceptedAt,current=false}){
 const definition=policies.profiles[p?.profile];if(!definition)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');
 const fields=[...definition.payloadRequiredFields];if(p.reasonCode==='COMPROMISE')fields.push('evidenceRefs');exact(p,fields);
 if(p.schemaVersion!==1||p.authorityOwner!=='HORIZON_RADAR_OWNER')fail('ADMIN_GRANT_AUTHORITY_MISMATCH');
 const role=p.profile.startsWith('HUMAN_')?policies.human:policies.domain,admin=rootState.principals.find(x=>x.principalId===p.adminPrincipalId),key=admin?.keys.find(k=>k.keyId===p.adminKeyId);
 if(!admin||admin.role!==role.role)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');lifecycle(admin,p.signedAt);lifecycle(key,p.signedAt);if(current){lifecycle(admin,acceptedAt,{current:true});lifecycle(key,acceptedAt,{current:true});}
 const snapshotAction=policies.snapshotProfile&&p.profile===policies.snapshotProfile.wireProfile,domainSnapshotAction=policies.domainSnapshotProfile&&p.profile===policies.domainSnapshotProfile.wireProfile;if(snapshotAction)verifySnapshotActionFields(p,policies.snapshotProfile);if(domainSnapshotAction)verifyDomainActionFields(p,policies.domainSnapshotProfile);const operation=snapshotAction?'HUMAN_VALIDATOR_TRUST_REGISTRY_ADMIN':domainSnapshotAction?'DOMAIN_REVIEW_TRUST_REGISTRY_ADMIN':role.operationScopes[p.actionType];if(!operation)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');const needed=[...new Set([...(Array.isArray(operation)?operation:[operation]),role===policies.human?'HUMAN_VALIDATOR_TRUST_REGISTRY_ADMIN':'DOMAIN_REVIEW_TRUST_REGISTRY_ADMIN'])].sort();
 if(!equal(p.scope,needed)||needed.some(s=>!admin.scopes.includes(s)))fail('ADMIN_GRANT_AUTHORITY_MISMATCH');
 if(time(p.createdAt)>time(p.signedAt)||time(p.signedAt)>time(acceptedAt))fail('INVALID_AUTHORITY_TIME');
 for(const field of ['validFrom','validUntil'])if(p[field]!==undefined&&p[field]!==null)time(p[field]);
 if(p.validFrom!==undefined&&(time(p.validFrom)<time(p.signedAt)||p.validUntil!==null&&time(p.validUntil)<time(p.validFrom)))fail('INVALID_AUTHORITY_TIME');
 if(p.grantId){const base={...p};delete base.grantId;const prefix=role===policies.human?'human-validator-grant':'domain-reviewer-grant';if(p.grantId!==prefix+':sha256:'+digest(base)||!Number.isSafeInteger(p.grantVersion)||p.grantVersion<1)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');}
 if(p.revocationId){const base={...p};delete base.revocationId;const prefix=role===policies.human?'human-validator-revocation':'domain-reviewer-revocation';if(p.revocationId!==prefix+':sha256:'+digest(base)||p.revokedAt!==p.signedAt)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');if(p.reasonCode==='COMPROMISE'){if(p.targetType!=='KEY'||p.retroactive!==true||time(p.invalidFrom)>time(p.revokedAt)||!Array.isArray(p.evidenceRefs)||!p.evidenceRefs.length)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');}else if(p.reasonCode!=='ADMINISTRATIVE_WITHDRAWAL'||p.retroactive!==false||p.invalidFrom!==null)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');}
 return {admin,key,role};
}
export function verifyAdminAction(action,context){exact(action,['payload','canonicalPayloadHash','signature']);const info=authorizeAdminPayload(action.payload,context);if(action.canonicalPayloadHash!==digest(action.payload)||!signatureValid(action.payload,action.signature,info.key.publicKey))fail('ADMIN_GRANT_AUTHORITY_MISMATCH');return info;}
export function subjectIdentity(rootState,principalId,keyId,role,at,{current=false}={}){
 const principal=rootState.principals.find(x=>x.principalId===principalId);if(principal?.role!==role)fail('ROOT_ADMIN_AUTHORITY_BYPASS');lifecycle(principal,at,{current});const key=principal.keys.find(k=>k.keyId===keyId);lifecycle(key,at,{current});return {principal,key};
}
function enrollmentReceipt(rootState,principalId){return rootState.receipts.find(r=>r.payload.receiptType==='PRINCIPAL_ENROLLMENT'&&r.payload.principalId===principalId);}
/** Records are immutable signed actions; business identity and exact key grants remain separate. */
export function validateBusinessTransition(action,records,rootState,policies,{historical=false}={}){
 if(policies.snapshotProfile&&action.payload.profile===policies.snapshotProfile.wireProfile){verifySnapshotActionFields(action.payload,policies.snapshotProfile);return;}
 if(policies.domainSnapshotProfile&&action.payload.profile===policies.domainSnapshotProfile.wireProfile){verifyDomainActionFields(action.payload,policies.domainSnapshotProfile);return;}
 const p=action.payload,isHuman=p.profile.startsWith('HUMAN_'),role=isHuman?'HUMAN_VALIDATOR':'DOMAIN_REVIEWER',alias=isHuman?p.validatorId:p.reviewerId;
 if(p.profile.startsWith('DOMAIN_REFERENCE_'))return; // dedicated reference validation is performed by reference runtime
 const principalId=p.subjectPrincipalId??p.validatorPrincipalId??p.reviewerPrincipalId??p.targetPrincipalId;
 const keyId=p.subjectKeyId??p.newKeyId??p.validatorKeyId??p.reviewerKeyId??p.targetKeyId;
 const subject=rootState.principals.find(x=>x.principalId===principalId);if(subject?.role!==role||subject.roleBindings[isHuman?'validatorId':'reviewerId']!==alias||!isHuman&&subject.roleBindings.validatorId!==p.validatorId)fail('ROOT_ADMIN_AUTHORITY_BYPASS');lifecycle(subject,p.signedAt,{current:!historical});
 if(p.targetIdentity!==alias)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');
 const enrollment=records.map(r=>r.payload).find(r=>r.profile===(isHuman?'HUMAN_VALIDATOR_ENROLLMENT_1.0':'DOMAIN_REVIEWER_ENROLLMENT_1.0')&&r.targetIdentity===alias);
 if(p.profile.endsWith('ENROLLMENT_1.0')){
  if(enrollment||p.targetKey!==null||p.businessRole!==role||p.authenticationProfile!==(isHuman?'EXPLICIT_HUMAN_VALIDATION':'DOMAIN_REVIEW_REFERENCE_1.0')||p.rootEnrollmentReceiptHash!==digest(enrollmentReceipt(rootState,principalId))||!Array.isArray(p.allowedScopes)||!p.allowedScopes.length)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');return;
 }
 if(!enrollment||enrollment.subjectPrincipalId!==principalId)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');
 if(keyId){const {key}=subjectIdentity(rootState,principalId,keyId,role,p.signedAt,{current:!historical});if(p.targetKey!==keyId)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');
  if(p.proofOfPossession){const rolePolicy=isHuman?policies.human:policies.domain,proof=p.proofOfPossession;exact(proof,['payload','signature']);exact(proof.payload,rolePolicy.proofOfPossessionProfile.requiredPayloadFields);const receiptHash=p.rootKeyRegistrationReceiptHash??p.rootKeyRotationReceiptHash;const expected={profile:rolePolicy.proofOfPossessionProfile.profile,...(isHuman?{validatorId:p.validatorId}:{reviewerId:p.reviewerId,validatorId:p.validatorId}),subjectPrincipalId:principalId,subjectKeyId:keyId,publicKey:key.publicKey,rootKeyReceiptHash:receiptHash,operationId:p.operationId,operationNonce:p.operationNonce};if(!equal(proof.payload,expected)||!signatureValid(expected,proof.signature,key.publicKey)||sha256(Buffer.from(key.publicKey,'base64'))!==(p.publicKeyFingerprint??p.newPublicKeyFingerprint)||(p.publicKey??p.newPublicKey)!==key.publicKey||!rootState.receipts.some(r=>digest(r)===receiptHash&&(r.payload.principalKeyId===keyId||r.payload.newKeyId===keyId)))fail('ADMIN_GRANT_AUTHORITY_MISMATCH');if(!equal(p.allowedScopes,enrollment.allowedScopes))fail('ADMIN_GRANT_AUTHORITY_MISMATCH');}
 }
 if(p.grantId&&!p.revocationId){const registration=records.map(r=>r.payload).find(r=>r.subjectPrincipalId===principalId&&(r.subjectKeyId===keyId||r.newKeyId===keyId)&&r.proofOfPossession);if(!registration)fail('ADMIN_GRANT_AUTHORITY_MISMATCH');if(isHuman){if(!enrollment.allowedScopes.some(s=>equal(s,p.authorizedScope)))fail('ADMIN_GRANT_AUTHORITY_MISMATCH');}else if(!enrollment.allowedScopes.some(s=>['sourceFamily','eventType','domain','rubricId','rubricVersion','reviewType'].every(k=>s[k]===p[k])))fail('ADMIN_GRANT_AUTHORITY_MISMATCH');
 const previous=records.map(r=>r.payload).filter(r=>r.grantId&&!r.revocationId&&r.targetIdentity===alias&&(isHuman?equal(r.authorizedScope,p.authorizedScope):['sourceFamily','eventType','domain','rubricId','rubricVersion','reviewType'].every(k=>r[k]===p[k]))).at(-1);if(p.grantVersion!==(previous?previous.grantVersion+1:1)||p.supersedesGrantId!==(previous?.grantId??null))fail('ADMIN_GRANT_AUTHORITY_MISMATCH');}
}
async function directory(p){await mkdir(p,{recursive:true,mode:0o700});const s=await lstat(p);if(!s.isDirectory()||s.isSymbolicLink()||s.mode&0o077)fail('UNSAFE_AUTHORITY_DIRECTORY');}
async function sync(p){const f=await open(p,'r');try{await f.sync();}finally{await f.close();}}
async function write(p,x){const f=await open(p,'wx',0o600);try{await f.writeFile(JSON.stringify(x)+'\n');await f.sync();}finally{await f.close();}await sync(resolve(p,'..'));}
async function replace(p,x){const temp=p+'.'+randomUUID()+'.tmp';await write(temp,x);await rename(temp,p);await sync(resolve(p,'..'));}
async function read(p){return JSON.parse(await readFile(p));}
/** Implements the frozen A->S->U->C->N hash DAG and pair+journal commit boundary. */
export class AdministrationStore {
 constructor({path,anchor,bootstrap,policies,signer,now=()=>new Date().toISOString(),fault=()=>{}}){this.path=resolve(path);this.anchor=resolve(anchor);this.bootstrap=bootstrap;this.policies=policies;this.signer=signer;this.now=now;this.fault=fault;if([this.path,this.anchor].some(p=>p.includes('/horizon-production/')))fail('PRODUCTION_IDENTITY_STORE_FORBIDDEN');}
 async locked(fn){for(const p of [this.path,this.anchor,join(this.path,'transactions')])await directory(p);const lock=await open(join(this.path,'lock'),'wx',0o600);try{return await fn();}finally{await lock.close();await unlink(join(this.path,'lock'));await sync(this.path);}}
 async verifyBundle(bundle,rootState){const {action,state,audit,receipt,head}=bundle;const info=verifyAdminAction(action,{rootState,policies:this.policies,acceptedAt:audit.payload.auditTimestamp});const key=info.key.publicKey,A=digest(action.payload),S=digest(state);if(!equal(state,{profile:'ADMIN_STATE_1.0',previousAuthorityHeadHash:action.payload.previousAuthorityHeadHash,actionHash:A,records:state.records})||!equal(state.records.at(-1),action))fail('CAPABILITY_STORE_UNAVAILABLE_OR_CORRUPT');
 const p=action.payload,common={operationId:p.operationId,adminPrincipalId:p.adminPrincipalId,adminKeyId:p.adminKeyId,actionType:p.actionType,targetIdentity:p.targetIdentity,targetKey:p.targetKey,scope:p.scope,signedAt:p.signedAt,result:'COMMITTED',auditTimestamp:audit.payload.auditTimestamp,previousHeadHash:p.previousAuthorityHeadHash};
 const up={profile:'ADMIN_AUDIT_1.0',...common,actionHash:A,stateHash:S};if(!equal(audit.payload,up)||audit.hash!==digest(up)||!signatureValid(up,audit.signature,key))fail('BLOCKED_ADMIN_AUDIT_UNAVAILABLE');
 const cp={profile:'ADMIN_RECEIPT_1.0',...common,payloadHash:A,actionSignature:action.signature,stateHash:S,auditHash:audit.hash,transactionId:receipt.payload.transactionId};if(!equal(receipt.payload,cp)||receipt.hash!==digest(cp)||!signatureValid(cp,receipt.signature,key))fail('BLOCKED_ADMIN_AUDIT_UNAVAILABLE');const np={profile:'ADMIN_COMMITTED_HEAD_1.0',previousHeadHash:p.previousAuthorityHeadHash,stateHash:S,auditHash:audit.hash,receiptHash:receipt.hash,transactionId:cp.transactionId};if(head!==digest(np))fail('CAPABILITY_STORE_UNAVAILABLE_OR_CORRUPT');return true;
 }
 async load(){const rootState=(await this.bootstrap.load()).state;try{const pointer=await read(join(this.path,'current.json')),anchor=await read(join(this.anchor,'current.json'));if(!equal(pointer,anchor))fail('CAPABILITY_STORE_UNAVAILABLE_OR_CORRUPT');const bundle=await read(join(this.path,'transactions',pointer.transactionId+'.json')),journal=await read(join(this.path,'transactions',pointer.transactionId+'.journal.json'));if(journal.state!=='COMMITTED'||journal.head!==pointer.head||bundle.head!==pointer.head)fail('CAPABILITY_STORE_UNAVAILABLE_OR_CORRUPT');await this.verifyBundle(bundle,rootState);
 let prior=null,records=[];const visited=new Set();const chain=[];let b=bundle;while(b){if(visited.has(b.head))fail('CAPABILITY_STORE_UNAVAILABLE_OR_CORRUPT');visited.add(b.head);chain.unshift(b);const prev=b.action.payload.previousAuthorityHeadHash;if(prev===null)break;const previousPointer=await read(join(this.path,prev+'.head.json'));const j=await read(join(this.path,'transactions',previousPointer.transactionId+'.journal.json'));if(j.state!=='COMMITTED'||j.head!==prev)fail('CAPABILITY_STORE_UNAVAILABLE_OR_CORRUPT');b=await read(join(this.path,'transactions',previousPointer.transactionId+'.json'));if(b.head!==prev)fail('CAPABILITY_STORE_UNAVAILABLE_OR_CORRUPT');}
 for(const item of chain){await this.verifyBundle(item,rootState);if(item.action.payload.previousAuthorityHeadHash!==prior||!equal(item.state.records,[...records,item.action]))fail('CAPABILITY_HISTORY_REWRITE_FORBIDDEN');validateBusinessTransition(item.action,records,rootState,this.policies,{historical:true});records=item.state.records;prior=item.head;}
 return {head:bundle.head,records,rootState,bundle,healthy:true,complete:true,ownerAuthenticated:true};}catch(error){fail(error.code??'CAPABILITY_STORE_UNAVAILABLE_OR_CORRUPT');}}
 async loadAtHead(head){
 const rootState=(await this.bootstrap.load()).state,chain=[],seen=new Set;let current=head;
 while(current!==null){if(seen.has(current))fail('CAPABILITY_HISTORY_REWRITE_FORBIDDEN');seen.add(current);const pointer=await read(join(this.path,current+'.head.json')),journal=await read(join(this.path,'transactions',pointer.transactionId+'.journal.json')),bundle=await read(join(this.path,'transactions',pointer.transactionId+'.json'));if(pointer.head!==current||journal.state!=='COMMITTED'||journal.head!==current||bundle.head!==current)fail('RECOVERY_REQUIRED');await this.verifyBundle(bundle,rootState);chain.unshift(bundle);current=bundle.action.payload.previousAuthorityHeadHash;}
 let records=[];for(const bundle of chain){if(!equal(bundle.state.records,[...records,bundle.action]))fail('CAPABILITY_HISTORY_REWRITE_FORBIDDEN');validateBusinessTransition(bundle.action,records,rootState,this.policies,{historical:true});records=bundle.state.records;}return {healthy:true,complete:true,ownerAuthenticated:true,rootState,head,records,bundle:chain.at(-1)};
 }
 async prepareBundle(action,before){
 verifyAdminAction(action,{rootState:before.rootState,policies:this.policies,acceptedAt:this.now(),current:true});if(action.payload.previousAuthorityHeadHash!==before.head)fail('CAPABILITY_HEAD_CONFLICT');validateBusinessTransition(action,before.records,before.rootState,this.policies);
 const authorized=verifyAdminAction(action,{rootState:before.rootState,policies:this.policies,acceptedAt:this.now(),current:true});if(await this.signer.public()!==authorized.key.publicKey)fail('SNAPSHOT_SIGNING_AUTHORITY_MISMATCH');
 const p=action.payload,A=digest(p),state={profile:'ADMIN_STATE_1.0',previousAuthorityHeadHash:before.head,actionHash:A,records:[...before.records,action]},S=digest(state),transactionId=randomUUID(),common={operationId:p.operationId,adminPrincipalId:p.adminPrincipalId,adminKeyId:p.adminKeyId,actionType:p.actionType,targetIdentity:p.targetIdentity,targetKey:p.targetKey,scope:p.scope,signedAt:p.signedAt,result:'COMMITTED',auditTimestamp:this.now(),previousHeadHash:before.head};
 const up={profile:'ADMIN_AUDIT_1.0',...common,actionHash:A,stateHash:S},audit={payload:up,hash:digest(up),signature:await this.signer.sign(Buffer.from(canonical(up)))},cp={profile:'ADMIN_RECEIPT_1.0',...common,payloadHash:A,actionSignature:action.signature,stateHash:S,auditHash:audit.hash,transactionId},receipt={payload:cp,hash:digest(cp),signature:await this.signer.sign(Buffer.from(canonical(cp)))},head=digest({profile:'ADMIN_COMMITTED_HEAD_1.0',previousHeadHash:before.head,stateHash:S,auditHash:audit.hash,receiptHash:receipt.hash,transactionId}),bundle={action,state,audit,receipt,head};await this.verifyBundle(bundle,before.rootState);return bundle;
 }
 async commit(action){if([this.policies.snapshotProfile?.wireProfile,this.policies.domainSnapshotProfile?.wireProfile].includes(action.payload.profile))fail('SNAPSHOT_ATOMICITY_CONFORMANCE_FAILURE');return this.locked(async()=>{let before;try{await lstat(join(this.path,'current.json'));before=await this.load();}catch(e){if(e.code!=='ENOENT')throw e;before={head:null,records:[],rootState:(await this.bootstrap.load()).state};}const duplicate=before.records.find(r=>r.payload.operationId===action.payload.operationId);if(duplicate){if(!equal(duplicate,action))fail('CONFLICTING_CAPABILITY_RECORD');return {terminal:'IDEMPOTENT',...before};}verifyAdminAction(action,{rootState:before.rootState,policies:this.policies,acceptedAt:this.now(),current:true});if(action.payload.previousAuthorityHeadHash!==before.head)fail('CAPABILITY_HEAD_CONFLICT');validateBusinessTransition(action,before.records,before.rootState,this.policies);
 const p=action.payload,A=digest(p),state={profile:'ADMIN_STATE_1.0',previousAuthorityHeadHash:before.head,actionHash:A,records:[...before.records,action]},S=digest(state),transactionId=randomUUID(),common={operationId:p.operationId,adminPrincipalId:p.adminPrincipalId,adminKeyId:p.adminKeyId,actionType:p.actionType,targetIdentity:p.targetIdentity,targetKey:p.targetKey,scope:p.scope,signedAt:p.signedAt,result:'COMMITTED',auditTimestamp:this.now(),previousHeadHash:before.head};
 const up={profile:'ADMIN_AUDIT_1.0',...common,actionHash:A,stateHash:S},audit={payload:up,hash:digest(up),signature:await this.signer.sign(Buffer.from(canonical(up)))},cp={profile:'ADMIN_RECEIPT_1.0',...common,payloadHash:A,actionSignature:action.signature,stateHash:S,auditHash:audit.hash,transactionId},receipt={payload:cp,hash:digest(cp),signature:await this.signer.sign(Buffer.from(canonical(cp)))},head=digest({profile:'ADMIN_COMMITTED_HEAD_1.0',previousHeadHash:before.head,stateHash:S,auditHash:audit.hash,receiptHash:receipt.hash,transactionId}),bundle={action,state,audit,receipt,head},pointer={head,transactionId};await this.verifyBundle(bundle,before.rootState);
 this.fault('audit-write');await write(join(this.path,'transactions',transactionId+'.json'),bundle);await write(join(this.path,'transactions',transactionId+'.journal.json'),{state:'PREPARED',head,previousPointer:before.bundle?{head:before.head,transactionId:before.bundle.receipt.payload.transactionId}:null});await write(join(this.path,head+'.head.json'),pointer);this.fault('before-pointer');await replace(join(this.path,'current.json'),pointer);this.fault('between-pointers');await replace(join(this.anchor,'current.json'),pointer);this.fault('before-committed');await replace(join(this.path,'transactions',transactionId+'.journal.json'),{state:'COMMITTED',head});return this.load();});}
}
export function businessEligibility(snapshot,{principalId,keyId,role,alias,scope,at,current=true}){try{const {records,rootState}=snapshot;if(!snapshot.healthy||!snapshot.complete||!snapshot.ownerAuthenticated)fail('AUTHORITY_UNAVAILABLE');subjectIdentity(rootState,principalId,keyId,role,at,{current});const isHuman=role==='HUMAN_VALIDATOR',enrollment=records.map(r=>r.payload).find(p=>p.targetIdentity===alias&&p.profile===(isHuman?'HUMAN_VALIDATOR_ENROLLMENT_1.0':'DOMAIN_REVIEWER_ENROLLMENT_1.0'));if(!enrollment) return {status:'NOT_ELIGIBLE',reason:'BUSINESS_ENROLLMENT_MISSING'};const grant=records.map(r=>r.payload).filter(p=>p.grantId&&!p.revocationId&&time(p.signedAt)<=time(at)&&p.targetIdentity===alias&&(isHuman?p.validatorKeyId:p.reviewerKeyId)===keyId&&(isHuman?equal(p.authorizedScope,scope):['sourceFamily','eventType','domain','rubricId','rubricVersion','reviewType'].every(k=>p[k]===scope[k]))).at(-1);if(!grant)return {status:'NOT_ELIGIBLE',reason:'EXACT_KEY_GRANT_MISSING'};if(time(at)<time(grant.validFrom)||grant.validUntil!==null&&time(at)>time(grant.validUntil))return {status:'NOT_ELIGIBLE',reason:'GRANT_EXPIRED'};for(const r of records.map(x=>x.payload).filter(p=>p.revocationId&&p.targetId===alias)){const matches=r.targetType==='SUBJECT'||r.targetType==='KEY'&&r.targetKeyId===keyId||r.targetType==='GRANT'&&r.grantId===grant.grantId;if(matches&&time(at)>=time(r.invalidFrom??r.revokedAt))return {status:'NOT_ELIGIBLE',reason:'BUSINESS_REVOKED'};}return {status:'ELIGIBLE',grant};}catch(e){return {status:'INVALID',reason:e.code??'AUTHORITY_UNAVAILABLE'};}}
