import {readFile,mkdir,open,rename,unlink,lstat,readdir} from 'node:fs/promises';import {join,resolve,dirname} from 'node:path';import {randomUUID} from 'node:crypto';
import {canonical} from '../radar-judgment/provider.mjs';import {exact,time,lifecycle,signatureValid,fail} from '../radar-bootstrap/index.mjs';import {verifyHumanEnvelope} from './authentication.mjs';import {businessEligibility,subjectIdentity,verifyAdminAction} from './administration.mjs';import {digest,same,inventory,compareEntries,snapshotIdentity,verifySnapshotContent,verifySnapshotActionFields} from './snapshot-profile.mjs';
const read=async p=>JSON.parse(await readFile(p));const exists=async p=>{try{await lstat(p);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}};
async function directory(p){await mkdir(p,{recursive:true,mode:0o700});const s=await lstat(p);if(!s.isDirectory()||s.isSymbolicLink()||(s.mode&0o077))fail('UNSAFE_AUTHORITY_DIRECTORY');}
async function sync(p){const f=await open(p,'r');try{await f.sync();}finally{await f.close();}}
async function write(p,x){const f=await open(p,'wx',0o600);try{await f.writeFile(JSON.stringify(x)+'\n');await f.sync();}finally{await f.close();}await sync(dirname(p));}
async function immutable(p,x){if(await exists(p)){if(!same(await read(p),x))fail('SNAPSHOT_CONFLICT_BLOCKED');return;}await write(p,x);}
async function replace(p,x){const t=p+'.'+randomUUID()+'.tmp';await write(t,x);await rename(t,p);await sync(dirname(p));}
/** Resolve each row against independently authenticated Root + administration history. */
export function verifyHumanEntry(entry,administration,{current=false}={}){
 try{const {record,payload,signature}=entry;exact(entry,['record','payload','signature','envelopeHash','validatorPrincipalId','validatorEnrollmentReceiptHash','validatorKeyRegistrationReceiptHash','validatorGrantId','validatorGrantHash']);if(entry.envelopeHash!==digest({record,payload,signature}))fail('INVALID_SNAPSHOT_CONTENT');
 const principal=administration.rootState.principals.find(p=>p.principalId===entry.validatorPrincipalId);if(principal?.roleBindings.validatorId!==payload.validatorId||record.validatorAuthorityRef!==payload.validatorId||record.provenance.authenticationRef!==payload.validatorId||record.validationType!=='ENTITY_LEVEL'||payload.schemaVersion!==1||!Array.isArray(payload.attestedFields)||!same(payload.attestedFields,['ENTITY_LEVEL']))fail('INVALID_SNAPSHOT_CONTENT');
 const {key}=subjectIdentity(administration.rootState,entry.validatorPrincipalId,payload.keyId,'HUMAN_VALIDATOR',payload.signedAt,{current});
 const rootReceipt=administration.rootState.receipts.find(r=>r.payload.receiptType==='PRINCIPAL_ENROLLMENT'&&r.payload.principalId===principal.principalId);if(digest(rootReceipt)!==entry.validatorEnrollmentReceiptHash)fail('INVALID_SNAPSHOT_CONTENT');
 const registration=administration.records.find(r=>r.payload.subjectPrincipalId===principal.principalId&&(r.payload.subjectKeyId===payload.keyId||r.payload.newKeyId===payload.keyId)&&r.payload.proofOfPossession);if(!registration||digest(registration)!==entry.validatorKeyRegistrationReceiptHash)fail('INVALID_SNAPSHOT_CONTENT');
 const eligibility=businessEligibility(administration,{principalId:principal.principalId,keyId:payload.keyId,role:'HUMAN_VALIDATOR',alias:payload.validatorId,scope:record.scope,at:payload.signedAt,current});if(eligibility.status!=='ELIGIBLE'||eligibility.grant.grantId!==entry.validatorGrantId||digest(eligibility.grant)!==entry.validatorGrantHash)fail('INVALID_SNAPSHOT_CONTENT');
 const grant=eligibility.grant;if(!same(grant.rubricScope,{rubricId:payload.rubricId,rubricVersion:payload.rubricVersion}))fail('INVALID_SNAPSHOT_CONTENT');time(payload.signedAt);time(payload.createdAt);if(time(payload.createdAt)>time(payload.signedAt)||time(record.validatedAt)>time(payload.signedAt))fail('INVALID_SNAPSHOT_CONTENT');
 const trust={healthy:true,complete:true,ownerAuthenticated:true,validators:[{validatorId:payload.validatorId,status:principal.status,validFrom:principal.validFrom,validUntil:principal.validUntil,revokedAt:principal.revokedAt,allowedScopes:[record.scope]}],keys:[{...key,validatorId:payload.validatorId,algorithm:'Ed25519',revocationReason:key.invalidFrom?'COMPROMISE':null}]};if(verifyHumanEnvelope({record,payload,signature},trust).status!=='VERIFIED')fail('INVALID_SNAPSHOT_CONTENT');return true;
 }catch(e){fail(e.code??'INVALID_SNAPSHOT_CONTENT');}
}
export function bindHumanEnvelope(envelope,administration){const principal=administration.rootState.principals.find(p=>p.role==='HUMAN_VALIDATOR'&&p.roleBindings.validatorId===envelope.payload.validatorId),registration=administration.records.find(r=>r.payload.subjectPrincipalId===principal?.principalId&&(r.payload.subjectKeyId===envelope.payload.keyId||r.payload.newKeyId===envelope.payload.keyId)&&r.payload.proofOfPossession),eligibility=businessEligibility(administration,{principalId:principal?.principalId,keyId:envelope.payload.keyId,role:'HUMAN_VALIDATOR',alias:envelope.payload.validatorId,scope:envelope.record.scope,at:envelope.payload.signedAt,current:true});if(eligibility.status!=='ELIGIBLE')fail('SNAPSHOT_SIGNING_BLOCKED');const entry={...envelope,envelopeHash:digest(envelope),validatorPrincipalId:principal.principalId,validatorEnrollmentReceiptHash:digest(administration.rootState.receipts.find(r=>r.payload.receiptType==='PRINCIPAL_ENROLLMENT'&&r.payload.principalId===principal.principalId)),validatorKeyRegistrationReceiptHash:digest(registration),validatorGrantId:eligibility.grant.grantId,validatorGrantHash:digest(eligibility.grant)};verifyHumanEntry(entry,administration,{current:true});return entry;}
/** Isolated profile-bound Store. Outer transaction joins exact Admin DAG to protected Store anchor. */
export class HumanValidationStore {
 constructor({path,anchor,administration,profile,now=()=>new Date().toISOString(),fault=()=>{}}){this.path=resolve(path);this.anchor=resolve(anchor);this.administration=administration;this.profile=profile;this.now=now;this.fault=fault;const scope=profile.storeScope;if(scope.environment!=='NON_PRODUCTION_TEST'||[this.path,this.anchor].some(p=>p.includes('horizon-production')))fail('SNAPSHOT_SIGNING_AUTHORITY_MISMATCH');}
 async locked(fn){return this.administration.locked(async()=>{for(const p of [this.path,this.anchor,...['anchors','admissions','envelopes','snapshots','transactions'].map(d=>join(this.path,d))])await directory(p);const f=await open(join(this.path,'lock'),'wx',0o600);try{return await fn();}finally{await f.close();await unlink(join(this.path,'lock'));await sync(this.path);}});}
 async initialize(binding){return this.locked(async()=>{const expected=this.profile.constraintPayload.completeness.integrityMetadata.initializationConstants;if(!same(binding,expected))fail('SNAPSHOT_SIGNING_AUTHORITY_MISMATCH');if(await exists(join(this.anchor,'initialization.json'))||await exists(join(this.path,'current.json')))fail('SNAPSHOT_CONFLICT_BLOCKED');for(const d of ['anchors','admissions','envelopes','snapshots','transactions'])if((await readdir(join(this.path,d))).length)fail('SNAPSHOT_SIGNING_BLOCKED');const admin=await this.administration.load(),a={profile:'HUMAN_STORE_PROTECTED_ANCHOR_1.0',storeId:binding.storeId,environment:binding.environment,initializationBindingHash:digest(binding),generation:0,admissionHeadHash:null,admissionCount:0,snapshotId:null,snapshotHash:null,administrationHeadHash:admin.head,transactionId:null};await write(join(this.anchor,'initialization.json'),binding);await write(join(this.path,'anchors',digest(a)+'.json'),a);await replace(join(this.path,'current.json'),a);await replace(join(this.anchor,'current.json'),a);return a;});}
 async census(anchor,administration){exact(anchor,this.profile.constraintPayload.completeness.integrityMetadata.storeAnchorKeys);if(anchor.profile!=='HUMAN_STORE_PROTECTED_ANCHOR_1.0'||anchor.storeId!==this.profile.storeScope.storeId||anchor.environment!==this.profile.storeScope.environment||!Number.isSafeInteger(anchor.generation)||anchor.generation<0||!Number.isSafeInteger(anchor.admissionCount)||anchor.admissionCount<0||(anchor.admissionHeadHash===null)!==(anchor.admissionCount===0))fail('INVALID_SNAPSHOT_BINDING');const binding=await read(join(this.anchor,'initialization.json'));if(!same(binding,this.profile.constraintPayload.completeness.integrityMetadata.initializationConstants)||digest(binding)!==anchor.initializationBindingHash)fail('INVALID_SNAPSHOT_BINDING');const entries=[],seen=new Set;let h=anchor.admissionHeadHash,sequence=anchor.admissionCount;while(h!==null){if(seen.has(h)||sequence<1)fail('INVALID_SNAPSHOT_CONTENT');seen.add(h);const row=await read(join(this.path,'admissions',h+'.json'));exact(row,this.profile.constraintPayload.completeness.integrityMetadata.admissionJournalRowKeys);if(digest(row)!==h||row.sequence!==sequence||row.storeId!==anchor.storeId||row.environment!==anchor.environment||row.profile!=='HUMAN_STORE_ADMISSION_INTEGRITY_1.0')fail('INVALID_SNAPSHOT_CONTENT');const j=await read(join(this.path,'transactions',row.transactionId+'.json'));if(j.kind!=='ADMISSION'||j.state!=='COMMITTED'||j.admissionHash!==h)fail('RECOVERY_REQUIRED');const e=await read(join(this.path,'envelopes',row.envelopeHash+'.json'));if(e.envelopeHash!==row.envelopeHash||e.record.validationId!==row.validationId||e.record.recordVersion!==row.recordVersion)fail('INVALID_SNAPSHOT_CONTENT');verifyHumanEntry(e,administration);entries.push(e);h=row.previousAdmissionHash;sequence--;}
 if(sequence!==0)fail('INVALID_SNAPSHOT_CONTENT');entries.sort(compareEntries);const ids=new Set;for(const e of entries){const id=canonical([e.record.validationId,e.record.recordVersion]);if(ids.has(id))fail('INVALID_SNAPSHOT_CONTENT');ids.add(id);}return entries;}
 async verifyAnchorHistory(current){let a=current;const seen=new Set;while(a.generation>0){const h=digest(a);if(seen.has(h))fail('INVALID_SNAPSHOT_BINDING');seen.add(h);const j=await read(join(this.path,'transactions',a.transactionId+'.json'));if(j.state!=='COMMITTED'||j.targetAnchorHash!==h)fail('RECOVERY_REQUIRED');const previous=await read(join(this.path,'anchors',j.previousAnchorHash+'.json'));if(previous.generation+1!==a.generation||previous.initializationBindingHash!==a.initializationBindingHash||previous.admissionCount>a.admissionCount)fail('INVALID_SNAPSHOT_BINDING');a=previous;}if(a.admissionCount!==0||a.snapshotId!==null||a.snapshotHash!==null||a.admissionHeadHash!==null||a.transactionId!==null)fail('INVALID_SNAPSHOT_BINDING');return seen;}
 async pending(){for(const n of await readdir(join(this.path,'transactions'))){const j=await read(join(this.path,'transactions',n));if(j.state==='PREPARED')fail('RECOVERY_REQUIRED');}}
 async cut(){await this.pending();const a=await read(join(this.anchor,'current.json')),pointer=await read(join(this.path,'current.json'));if(!same(a,pointer))fail('RECOVERY_REQUIRED');await this.verifyAnchorHistory(a);const admin=await this.administration.load();return {anchor:a,entries:await this.census(a,admin),admin};}
 async admit(entry){return this.locked(async()=>{const cut=await this.cut();verifyHumanEntry(entry,cut.admin,{current:true});const previous=cut.entries.find(e=>e.record.validationId===entry.record.validationId&&e.record.recordVersion===entry.record.recordVersion);if(previous){if(!same(previous,entry))fail('SNAPSHOT_CONFLICT_BLOCKED');return {terminal:'IDEMPOTENT_EXISTING_RECORD',anchor:cut.anchor};}const transactionId=randomUUID(),row={profile:'HUMAN_STORE_ADMISSION_INTEGRITY_1.0',storeId:cut.anchor.storeId,environment:cut.anchor.environment,sequence:cut.anchor.admissionCount+1,transactionId,validationId:entry.record.validationId,recordVersion:entry.record.recordVersion,envelopeHash:entry.envelopeHash,previousAdmissionHash:cut.anchor.admissionHeadHash},admissionHash=digest(row),a={...cut.anchor,generation:cut.anchor.generation+1,admissionHeadHash:admissionHash,admissionCount:cut.anchor.admissionCount+1,transactionId},j={kind:'ADMISSION',state:'PREPARED',transactionId,admissionHash,previousAnchorHash:digest(cut.anchor),targetAnchorHash:digest(a)};
 await immutable(join(this.path,'envelopes',entry.envelopeHash+'.json'),entry);await immutable(join(this.path,'admissions',admissionHash+'.json'),row);await immutable(join(this.path,'anchors',digest(a)+'.json'),a);await write(join(this.path,'transactions',transactionId+'.json'),j);this.fault('admission-before-pointer');await replace(join(this.path,'current.json'),a);await replace(join(this.anchor,'current.json'),a);await replace(join(this.path,'transactions',transactionId+'.json'),{...j,state:'COMMITTED'});return {terminal:'COMMITTED',anchor:a};});}
 async verifyPackage(pkg,{administration,currentAnchor,current=false}={}){exact(pkg,['content','authorityContext','action','commitProof']);exact(pkg.authorityContext,['rootHistoryHeadHash','humanAdministrationHeadHash']);exact(pkg.commitProof,this.profile.constraintPayload.objectDefinition.commitProofKeys);verifySnapshotContent(pkg.content,this.profile);const p=pkg.action.payload;verifySnapshotActionFields(p,this.profile);if(digest(pkg.content)!==p.contentHash||pkg.content.recordCount!==p.recordCount||pkg.content.admissionLedgerHash!==p.admissionLedgerHash||digest(pkg.authorityContext)!==p.authorityContextHash||pkg.authorityContext.humanAdministrationHeadHash!==p.previousAuthorityHeadHash)fail('INVALID_SNAPSHOT_BINDING');
 const admin=administration??await this.administration.load();if(!admin.records.some(a=>same(a,pkg.action)))fail('INVALID_SNAPSHOT_BINDING');for(const e of pkg.content.entries)verifyHumanEntry(e,admin);const bundle=await read(join(this.administration.path,'transactions',pkg.commitProof.transactionId+'.json'));await this.administration.verifyBundle(bundle,admin.rootState);if(!same(bundle.action,pkg.action)||digest(bundle.state)!==pkg.commitProof.stateHash||bundle.audit.hash!==pkg.commitProof.auditHash||bundle.receipt.hash!==pkg.commitProof.receiptHash||bundle.head!==pkg.commitProof.committedHeadHash)fail('INVALID_SNAPSHOT_BINDING');
 const a=await read(join(this.path,'anchors',pkg.commitProof.storeAnchorHash+'.json'));if(digest(a)!==pkg.commitProof.storeAnchorHash||a.snapshotId!==p.snapshotId||a.snapshotHash!==pkg.action.canonicalPayloadHash||a.administrationHeadHash!==bundle.head||a.transactionId!==pkg.commitProof.transactionId)fail('INVALID_SNAPSHOT_BINDING');const j=await read(join(this.path,'transactions',a.transactionId+'.json'));if(j.state!=='COMMITTED'||j.snapshotHash!==a.snapshotHash||j.targetAnchorHash!==digest(a))fail('RECOVERY_REQUIRED');
 const top=currentAnchor??await read(join(this.anchor,'current.json')),ancestry=await this.verifyAnchorHistory(top);if(top.generation!==0&&!ancestry.has(digest(a)))fail('INVALID_SNAPSHOT_BINDING');if(!same(await this.census(a,admin),pkg.content.entries))fail('INVALID_SNAPSHOT_CONTENT');if(current&&!same(await this.census(top,admin),pkg.content.entries))fail('SNAPSHOT_SIGNING_BLOCKED');
 // Authority cut is retained in existing externally authenticated Root and Admin histories.
 const root=await this.administration.bootstrap.load();if(!root.anchor.history.some(h=>h.head===pkg.authorityContext.rootHistoryHeadHash))fail('INVALID_SNAPSHOT_BINDING');verifyAdminAction(pkg.action,{rootState:admin.rootState,policies:this.administration.policies,acceptedAt:bundle.audit.payload.auditTimestamp});
 const prior=await read(join(this.path,'anchors',j.previousAnchorHash+'.json'));if(p.previousSnapshotId!==prior.snapshotId||p.previousSnapshotHash!==prior.snapshotHash)fail('SNAPSHOT_CHAIN_CONFORMANCE_FAILURE');return true;}
 async load({historicalId}={}){const cut=await this.cut(),id=historicalId??cut.anchor.snapshotId;if(!id)fail('SNAPSHOT_SIGNING_BLOCKED');let pkg=await read(join(this.path,'snapshots',digest(id)+'.json'));const currentPackage=pkg,seen=new Set;while(pkg){if(seen.has(pkg.action.payload.snapshotId))fail('SNAPSHOT_CHAIN_CONFORMANCE_FAILURE');seen.add(pkg.action.payload.snapshotId);await this.verifyPackage(pkg,{administration:cut.admin,currentAnchor:cut.anchor,current:!historicalId&&pkg===currentPackage});const previous=pkg.action.payload.previousSnapshotId;pkg=previous===null?null:await read(join(this.path,'snapshots',digest(previous)+'.json'));}return {terminal:'SNAPSHOT_VERIFIED',healthy:true,complete:true,records:currentPackage.content.entries,package:currentPackage,anchor:cut.anchor};}
 async snapshot({checkpoint=false}={}){return this.locked(async()=>{const cut=await this.cut(),profile=this.profile,o=profile.constraintPayload.objectDefinition,entries=cut.entries,content={storeId:profile.storeScope.storeId,storeSchemaVersion:1,environment:profile.storeScope.environment,recordCount:entries.length,entries,admissionLedgerHash:digest(inventory(entries))};verifySnapshotContent(content,profile);const adminPrincipal=cut.admin.rootState.principals.find(p=>p.principalId===profile.storeScope.adminPrincipalId);lifecycle(adminPrincipal,this.now(),{current:true});if(adminPrincipal.role!=='HORIZON_HUMAN_VALIDATION_ADMIN'||!adminPrincipal.scopes.includes('HUMAN_VALIDATOR_TRUST_REGISTRY_ADMIN'))fail('SNAPSHOT_SIGNING_AUTHORITY_MISMATCH');const key=adminPrincipal.keys.find(k=>k.status==='ACTIVE');lifecycle(key,this.now(),{current:true});if(await this.administration.signer.public()!==key.publicKey)fail('SNAPSHOT_SIGNING_AUTHORITY_MISMATCH');
 if(!checkpoint&&cut.anchor.snapshotId){const old=await this.load({historicalId:cut.anchor.snapshotId});if(old.package.action.payload.contentHash===digest(content)&&old.package.action.payload.adminPrincipalId===adminPrincipal.principalId&&old.package.action.payload.adminKeyId===key.keyId)return {...old,terminal:'IDEMPOTENT_EXISTING_SNAPSHOT'};}
 const now=this.now(),root=await this.administration.bootstrap.load(),authorityContext={rootHistoryHeadHash:root.head,humanAdministrationHeadHash:cut.admin.head},p={...o.wireConstants,operationId:randomUUID(),operationNonce:randomUUID(),previousAuthorityHeadHash:cut.admin.head,adminPrincipalId:adminPrincipal.principalId,adminKeyId:key.keyId,signedAt:now,createdAt:now,profileConstraintHash:profile.constraintPayloadHash,snapshotId:'pending',contentHash:digest(content),recordCount:entries.length,admissionLedgerHash:content.admissionLedgerHash,authorityContextHash:digest(authorityContext),previousSnapshotId:cut.anchor.snapshotId,previousSnapshotHash:cut.anchor.snapshotHash};p.snapshotId=snapshotIdentity(p,profile);verifySnapshotActionFields(p,profile);
 // All complete entries were independently verified by cut before signing.
 const action={payload:p,canonicalPayloadHash:digest(p),signature:await this.administration.signer.sign(Buffer.from(canonical(p)))};verifyAdminAction(action,{rootState:cut.admin.rootState,policies:this.administration.policies,acceptedAt:this.now(),current:true});try{this.fault('audit-sign');}catch{fail('BLOCKED_ADMIN_AUDIT_UNAVAILABLE');}const bundle=await this.administration.prepareBundle(action,cut.admin),transactionId=bundle.receipt.payload.transactionId,a={...cut.anchor,generation:cut.anchor.generation+1,snapshotId:p.snapshotId,snapshotHash:action.canonicalPayloadHash,administrationHeadHash:bundle.head,transactionId},proof={transactionId,stateHash:digest(bundle.state),auditHash:bundle.audit.hash,receiptHash:bundle.receipt.hash,committedHeadHash:bundle.head,storeAnchorHash:digest(a)},pkg={content,authorityContext,action,commitProof:proof},j={profile:'HUMAN_STORE_SNAPSHOT_TRANSACTION_1.0',transactionId,state:'PREPARED',previousAnchorHash:digest(cut.anchor),targetAnchorHash:digest(a),previousAdministrationHeadHash:cut.admin.head,targetAdministrationHeadHash:bundle.head,snapshotId:p.snapshotId,snapshotHash:action.canonicalPayloadHash,contentHash:digest(content),authorityContextHash:digest(authorityContext),stateHash:proof.stateHash,auditHash:proof.auditHash,receiptHash:proof.receiptHash};exact(j,profile.constraintPayload.auditAtomicity.preparedJournal.requiredKeys);
 this.fault('snapshot-write');await immutable(join(this.path,'snapshots',digest(p.snapshotId)+'.json'),pkg);await immutable(join(this.path,'anchors',digest(a)+'.json'),a);this.fault('receipt-write');await immutable(join(this.administration.path,'transactions',transactionId+'.json'),bundle);await immutable(join(this.administration.path,bundle.head+'.head.json'),{head:bundle.head,transactionId});this.fault('audit-write');await write(join(this.path,'transactions',transactionId+'.json'),j);await immutable(join(this.administration.path,'transactions',transactionId+'.journal.json'),{state:'PREPARED',head:bundle.head});await this.publish(j,a);return this.load();});}
 async publish(j,a){const pointer={head:j.targetAdministrationHeadHash,transactionId:j.transactionId};this.fault('before-admin-pointer');await replace(join(this.administration.path,'current.json'),pointer);this.fault('between-admin-pointers');await replace(join(this.administration.anchor,'current.json'),pointer);this.fault('before-store-pointer');await replace(join(this.path,'current.json'),a);this.fault('between-store-pointers');await replace(join(this.anchor,'current.json'),a);this.fault('before-committed');if(!same(await read(join(this.path,'current.json')),a)||!same(await read(join(this.anchor,'current.json')),a)||!same(await read(join(this.administration.path,'current.json')),pointer)||!same(await read(join(this.administration.anchor,'current.json')),pointer))fail('RECOVERY_REQUIRED');await replace(join(this.administration.path,'transactions',j.transactionId+'.journal.json'),{state:'COMMITTED',head:pointer.head});await replace(join(this.path,'transactions',j.transactionId+'.json'),{...j,state:'COMMITTED'});}
 async recover(){return this.locked(async()=>{const journals=(await readdir(join(this.path,'transactions'))).map(n=>join(this.path,'transactions',n)),pending=[];for(const p of journals){const j=await read(p);if(j.state==='PREPARED')pending.push(j);}if(!pending.length)return {terminal:'IDEMPOTENT_RECOVERY',...(await this.load())};if(pending.length!==1)fail('RECOVERY_REQUIRED');const j=pending[0];if(j.kind==='ADMISSION')fail('RECOVERY_REQUIRED');exact(j,this.profile.constraintPayload.auditAtomicity.preparedJournal.requiredKeys);const a=await read(join(this.path,'anchors',j.targetAnchorHash+'.json')),prior=await read(join(this.path,'anchors',j.previousAnchorHash+'.json')),root=(await this.administration.bootstrap.load()).state,bundle=await read(join(this.administration.path,'transactions',j.transactionId+'.json')),pkg=await read(join(this.path,'snapshots',digest(j.snapshotId)+'.json'));
 if(digest(a)!==j.targetAnchorHash||digest(prior)!==j.previousAnchorHash||a.generation!==prior.generation+1||!same(pkg.action,bundle.action)||pkg.action.canonicalPayloadHash!==j.snapshotHash||digest(pkg.content)!==j.contentHash||digest(pkg.authorityContext)!==j.authorityContextHash||digest(bundle.state)!==j.stateHash||bundle.audit.hash!==j.auditHash||bundle.receipt.hash!==j.receiptHash||bundle.head!==j.targetAdministrationHeadHash)fail('RECOVERY_REQUIRED');exact(pkg,['content','authorityContext','action','commitProof']);exact(pkg.authorityContext,['rootHistoryHeadHash','humanAdministrationHeadHash']);exact(pkg.commitProof,this.profile.constraintPayload.objectDefinition.commitProofKeys);
 const expectedAnchor={...prior,generation:prior.generation+1,snapshotId:j.snapshotId,snapshotHash:j.snapshotHash,administrationHeadHash:j.targetAdministrationHeadHash,transactionId:j.transactionId},expectedProof={transactionId:j.transactionId,stateHash:j.stateHash,auditHash:j.auditHash,receiptHash:j.receiptHash,committedHeadHash:j.targetAdministrationHeadHash,storeAnchorHash:j.targetAnchorHash},p=pkg.action.payload;
 if(!same(a,expectedAnchor)||!same(pkg.commitProof,expectedProof)||p.previousSnapshotId!==prior.snapshotId||p.previousSnapshotHash!==prior.snapshotHash||p.previousAuthorityHeadHash!==j.previousAdministrationHeadHash||pkg.authorityContext.humanAdministrationHeadHash!==j.previousAdministrationHeadHash||p.contentHash!==digest(pkg.content)||p.recordCount!==pkg.content.recordCount||p.admissionLedgerHash!==pkg.content.admissionLedgerHash||p.authorityContextHash!==digest(pkg.authorityContext))fail('RECOVERY_REQUIRED');
 const rootLoad=await this.administration.bootstrap.load();if(!rootLoad.anchor.history.some(h=>h.head===pkg.authorityContext.rootHistoryHeadHash))fail('RECOVERY_REQUIRED');
 const oldPointer=await read(join(this.administration.path,j.previousAdministrationHeadHash+'.head.json')),oldJournal=await read(join(this.administration.path,'transactions',oldPointer.transactionId+'.journal.json')),oldBundle=await read(join(this.administration.path,'transactions',oldPointer.transactionId+'.json'));if(oldJournal.state!=='COMMITTED'||oldJournal.head!==j.previousAdministrationHeadHash||oldBundle.head!==j.previousAdministrationHeadHash||!same(bundle.state.records,[...oldBundle.state.records,pkg.action]))fail('RECOVERY_REQUIRED');await this.administration.verifyBundle(oldBundle,root);await this.verifyAnchorHistory(prior);const historicalAdmin=await this.administration.loadAtHead(j.previousAdministrationHeadHash);let oldId=prior.snapshotId;const visited=new Set;while(oldId!==null){if(visited.has(oldId))fail('RECOVERY_REQUIRED');visited.add(oldId);const oldPkg=await read(join(this.path,'snapshots',digest(oldId)+'.json'));await this.verifyPackage(oldPkg,{administration:historicalAdmin,currentAnchor:prior});oldId=oldPkg.action.payload.previousSnapshotId;}
 verifySnapshotActionFields(pkg.action.payload,this.profile);verifySnapshotContent(pkg.content,this.profile);await this.administration.verifyBundle(bundle,root);verifyAdminAction(pkg.action,{rootState:root,policies:this.administration.policies,acceptedAt:this.now(),current:true});const administration={healthy:true,complete:true,ownerAuthenticated:true,records:bundle.state.records,rootState:root};if(!same(await this.census(prior,administration),pkg.content.entries))fail('RECOVERY_REQUIRED');
 for(const [file,allowed]of [[join(this.path,'current.json'),[digest(prior),digest(a)]],[join(this.anchor,'current.json'),[digest(prior),digest(a)]]])if(!allowed.includes(digest(await read(file))))fail('RECOVERY_REQUIRED');for(const file of [join(this.administration.path,'current.json'),join(this.administration.anchor,'current.json')])if(![j.previousAdministrationHeadHash,j.targetAdministrationHeadHash].includes((await read(file)).head))fail('RECOVERY_REQUIRED');await this.publish(j,a);return this.load();});}
}
