import {readFile} from 'node:fs/promises';import {join} from 'node:path';
import {canonical,sha256} from '../radar-judgment/provider.mjs';import {exact,time,fail} from '../radar-bootstrap/index.mjs';
export const SNAPSHOT_CONSTRAINT_HASH='e7447e84832d92e06f3e723136a01b1ef04380186a8854bb89697d55d949f90c';
export const digest=value=>sha256(canonical(value));export const same=(a,b)=>canonical(a)===canonical(b);
export async function loadSnapshotProfile(directory){const profile=JSON.parse(await readFile(join(directory,'radar-human-store-snapshot-signing-profile-v1.json')));if(profile.status!=='FROZEN / SEMANTIC DECISION'||digest(profile.constraintPayload)!==SNAPSHOT_CONSTRAINT_HASH||profile.constraintPayloadHash!==SNAPSHOT_CONSTRAINT_HASH)fail('SNAPSHOT_PROFILE_CONFORMANCE_FAILURE');return profile;}
export function compareEntries(a,b){const tuple=e=>[e.record.validationId,e.record.recordVersion,e.payload.keyId,e.payload.signedAt,e.envelopeHash],aa=tuple(a),bb=tuple(b);for(let i=0;i<aa.length;i++){if(aa[i]<bb[i])return -1;if(aa[i]>bb[i])return 1;}return 0;}
export const inventory=entries=>entries.map(e=>({validationId:e.record.validationId,recordVersion:e.record.recordVersion,envelopeHash:e.envelopeHash}));
export function snapshotIdentity(payload,profile){const keys=profile.constraintPayload.objectDefinition.identityPayloadKeys;return 'human-validation-store-snapshot:sha256:'+digest(Object.fromEntries(keys.map(k=>[k,payload[k]])));}
export function verifySnapshotActionFields(payload,profile){const o=profile.constraintPayload.objectDefinition;exact(payload,o.signedPayloadRequiredFields);for(const [k,v]of Object.entries(o.wireConstants))if(!same(payload[k],v))fail('SNAPSHOT_SIGNING_AUTHORITY_MISMATCH');if(payload.adminPrincipalId!==profile.storeScope.adminPrincipalId||payload.profileConstraintHash!==SNAPSHOT_CONSTRAINT_HASH)fail('SNAPSHOT_SIGNING_AUTHORITY_MISMATCH');for(const k of ['contentHash','admissionLedgerHash','authorityContextHash','profileConstraintHash'])if(!/^[a-f0-9]{64}$/.test(payload[k]))fail('INVALID_SNAPSHOT_BINDING');if(!Number.isSafeInteger(payload.recordCount)||payload.recordCount<0)fail('INVALID_SNAPSHOT_BINDING');if((payload.previousSnapshotId===null)!==(payload.previousSnapshotHash===null)||payload.previousSnapshotHash!==null&&!/^[a-f0-9]{64}$/.test(payload.previousSnapshotHash))fail('SNAPSHOT_CHAIN_CONFORMANCE_FAILURE');for(const k of ['operationId','operationNonce','adminKeyId','snapshotId'])if(typeof payload[k]!=='string'||!payload[k])fail('INVALID_SNAPSHOT_BINDING');time(payload.createdAt);time(payload.signedAt);if(payload.snapshotId!==snapshotIdentity(payload,profile))fail('INVALID_SNAPSHOT_BINDING');}
export function verifySnapshotContent(content,profile){exact(content,profile.constraintPayload.objectDefinition.contentKeys);if(content.storeId!==profile.storeScope.storeId||content.environment!==profile.storeScope.environment||content.storeSchemaVersion!==1||!Array.isArray(content.entries)||content.recordCount!==content.entries.length)fail('INVALID_SNAPSHOT_CONTENT');const ids=new Set;for(let i=0;i<content.entries.length;i++){const e=content.entries[i];exact(e,profile.constraintPayload.objectDefinition.entryKeys);if(i&&compareEntries(content.entries[i-1],e)>=0)fail('INVALID_SNAPSHOT_CONTENT');const id=canonical([e.record.validationId,e.record.recordVersion]);if(ids.has(id))fail('INVALID_SNAPSHOT_CONTENT');ids.add(id);if(e.envelopeHash!==digest({record:e.record,payload:e.payload,signature:e.signature}))fail('INVALID_SNAPSHOT_CONTENT');}if(content.admissionLedgerHash!==digest(inventory(content.entries)))fail('INVALID_SNAPSHOT_CONTENT');}
