import {mkdir,open,readFile,rename,unlink,lstat}from'node:fs/promises';import {resolve,join}from'node:path';import {homedir}from'node:os';import {randomUUID}from'node:crypto';import {canonical,sha256}from'../radar-judgment/provider.mjs';
const digest=value=>sha256(canonical(value));
async function sync(path){const f=await open(path,'r');try{await f.sync();}finally{await f.close();}}
async function create(path,value){const f=await open(path,'wx',0o600);try{await f.writeFile(JSON.stringify(value)+'\n');await f.sync();}finally{await f.close();}await sync(resolve(path,'..'));}
async function replace(path,value){const tmp=path+'.'+randomUUID()+'.tmp';await create(tmp,value);await rename(tmp,path);await sync(resolve(path,'..'));}
/** Atomic immutable snapshots; Owner authenticity is an independent, explicitly configured port. */
export class CapabilitySnapshotStore {
 constructor({path,anchor,ownerPort,recordVerifier,fault=()=>{}}){this.path=resolve(path);this.anchor=resolve(anchor);this.ownerPort=ownerPort;this.recordVerifier=recordVerifier;this.fault=fault;this.held=false;const production=join(homedir(),'.local/state/horizon-production');if([this.path,this.anchor].some(p=>p===production||p.startsWith(production+'/')))throw Error('PRODUCTION_IDENTITY_STORE_FORBIDDEN');}
 async directory(path){await mkdir(path,{recursive:true,mode:0o700});const st=await lstat(path);if(!st.isDirectory()||st.isSymbolicLink()||st.mode&0o077)throw Error('CAPABILITY_STORE_UNSAFE');}
 async locked(fn){for(const p of [this.path,this.anchor,join(this.path,'snapshots'),join(this.path,'journals'),join(this.path,'audit')])await this.directory(p);let f;try{f=await open(join(this.path,'lock'),'wx',0o600);}catch{throw Error('CAPABILITY_LOCK_UNAVAILABLE');}this.held=true;try{return await fn();}finally{this.held=false;await f.close();await unlink(join(this.path,'lock'));await sync(this.path);}}
 async load(){try{const pointer=JSON.parse(await readFile(join(this.path,'current.json'))),anchor=JSON.parse(await readFile(join(this.anchor,'current.json')));if(canonical(pointer)!==canonical(anchor))throw Error('PAIR');const bundle=JSON.parse(await readFile(join(this.path,'snapshots',pointer.head+'.json'))),journal=JSON.parse(await readFile(join(this.path,'journals',pointer.transactionId+'.json'))),audit=JSON.parse(await readFile(join(this.path,'audit',pointer.transactionId+'.json')));if(digest(bundle)!==pointer.head||journal.state!=='COMMITTED'||journal.head!==pointer.head||audit.head!==pointer.head||bundle.payload.previousHead!==audit.previousHead||bundle.payload.generation!==pointer.generation||bundle.payload.transactionId!==pointer.transactionId||bundle.payload.stateHash!==digest(bundle.state)||await this.ownerPort?.verifySnapshot(bundle)!==true||!Array.isArray(bundle.state.records)||await this.recordVerifier?.(bundle.state.records)!==true)throw Error('INTEGRITY');return {head:pointer.head,generation:pointer.generation,state:bundle.state,healthy:true,complete:true,ownerAuthenticated:true};}catch{throw Error('CAPABILITY_STORE_UNAVAILABLE_OR_CORRUPT');}}
 async commit(state,{previousHead=null}={}){
  if(!this.held)throw Error('CAPABILITY_LOCK_REQUIRED');if(!this.ownerPort?.sealSnapshot||!this.ownerPort.verifySnapshot)throw Error('OWNER_ADMINISTRATION_AUTHORITY_UNAVAILABLE');if(await this.recordVerifier?.(state.records)!==true)throw Error('CAPABILITY_RECORD_INVALID');let generation=1;if(previousHead!==null){const before=await this.load();if(before.head!==previousHead)throw Error('CAPABILITY_HEAD_CONFLICT');if(canonical(state.records.slice(0,before.state.records.length))!==canonical(before.state.records))throw Error('CAPABILITY_HISTORY_REWRITE_FORBIDDEN');generation=before.generation+1;}else{try{await lstat(join(this.path,'current.json'));throw Error('CAPABILITY_ALREADY_INITIALIZED');}catch(e){if(e.code!=='ENOENT')throw e;}}
  const transactionId=randomUUID(),payload={generation,transactionId,previousHead,stateHash:digest(state)},bundle=await this.ownerPort.sealSnapshot({payload,state});if(canonical(bundle.payload)!==canonical(payload)||canonical(bundle.state)!==canonical(state)||await this.ownerPort.verifySnapshot(bundle)!==true)throw Error('OWNER_ADMINISTRATION_AUTHENTICATION_FAILED');const head=digest(bundle),pointer={head,generation,transactionId};
  this.fault('audit-write');await create(join(this.path,'audit',transactionId+'.json'),{head,previousHead,stateHash:payload.stateHash});await create(join(this.path,'snapshots',head+'.json'),bundle);await create(join(this.path,'journals',transactionId+'.json'),{head,state:'PREPARED'});this.fault('before-pointer');await replace(join(this.path,'current.json'),pointer);this.fault('between-pointers');await replace(join(this.anchor,'current.json'),pointer);this.fault('before-committed');await replace(join(this.path,'journals',transactionId+'.json'),{head,state:'COMMITTED'});return this.load();
 }
 async append(record,{identity}){return this.locked(async()=>{const before=await this.load(),existing=before.state.records.filter(r=>identity(r)===identity(record));if(existing.length){if(existing.length===1&&canonical(existing[0])===canonical(record))return {state:'IDEMPOTENT',head:before.head};throw Error('CONFLICTING_CAPABILITY_RECORD');}return this.commit({...before.state,records:[...before.state.records,record]},{previousHead:before.head});});}
}
