// RFC 8785 implementation copied byte-for-byte below from reviewed verifier; isolated Publisher identity verification only.
import {createHash}from'node:crypto';
const fail=code=>{throw Error(code)};
export function scalarString(s){if(typeof s!=='string')fail('INVALID_TYPE');for(let i=0;i<s.length;i++){const c=s.charCodeAt(i);if(c>=0xd800&&c<=0xdbff){const d=s.charCodeAt(++i);if(!(d>=0xdc00&&d<=0xdfff))fail('INVALID_UNICODE');}else if(c>=0xdc00&&c<=0xdfff)fail('INVALID_UNICODE');}return s;}
export function strictParse(text){if(typeof text!=='string')fail('INVALID_JSON');let i=0;const ws=()=>{while(i<text.length&&/[ \t\r\n]/.test(text[i]))i++};const string=()=>{const start=i;if(text[i++]!=='"')fail('INVALID_JSON');while(i<text.length){const c=text.charCodeAt(i++);if(c===34){let value;try{value=JSON.parse(text.slice(start,i))}catch{fail('INVALID_JSON')}return scalarString(value)}if(c<32)fail('INVALID_JSON');if(c===92){if(i>=text.length)fail('INVALID_JSON');const e=text[i++];if(e==='u'){if(!/^[0-9a-fA-F]{4}$/.test(text.slice(i,i+4)))fail('INVALID_JSON');i+=4}else if(!'"\\/bfnrt'.includes(e))fail('INVALID_JSON');}}fail('INVALID_JSON')};const value=()=>{ws();const c=text[i];if(c==='"')return string();if(c==='{'){i++;ws();const o=Object.create(null),seen=new Set();if(text[i]==='}'){i++;return o}for(;;){ws();if(text[i]!=='"')fail('INVALID_JSON');const k=string();if(seen.has(k))fail('DUPLICATE_KEY');seen.add(k);ws();if(text[i++]!==':')fail('INVALID_JSON');o[k]=value();ws();const end=text[i++];if(end==='}')return o;if(end!==',')fail('INVALID_JSON')}}if(c==='['){i++;ws();const a=[];if(text[i]===']'){i++;return a}for(;;){a.push(value());ws();const end=text[i++];if(end===']')return a;if(end!==',')fail('INVALID_JSON')}}for(const [literal,v]of [['true',true],['false',false],['null',null]])if(text.startsWith(literal,i)){i+=literal.length;return v}const match=/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/.exec(text.slice(i));if(!match)fail('INVALID_JSON');i+=match[0].length;const n=Number(match[0]);if(!Number.isFinite(n))fail('NON_FINITE_NUMBER');return n};const result=value();ws();if(i!==text.length)fail('INVALID_JSON');return result;}
const controls=new Map([[8,'\\b'],[9,'\\t'],[10,'\\n'],[12,'\\f'],[13,'\\r']]);
export function encodeString(s){scalarString(s);let out='"';for(const cp of s){const n=cp.codePointAt(0);if(n===34)out+='\\"';else if(n===92)out+='\\\\';else if(n<32)out+=controls.get(n)??'\\u'+n.toString(16).padStart(4,'0');else out+=cp}return out+'"'}
export function canonical(value){const active=new Set();function enc(v){if(v===null)return'null';if(typeof v==='string')return encodeString(v);if(typeof v==='boolean')return v?'true':'false';if(typeof v==='number'){if(!Number.isFinite(v))fail('NON_FINITE_NUMBER');return JSON.stringify(v)}if(typeof v!=='object')fail('UNSUPPORTED_TYPE');if(active.has(v))fail('CYCLIC_VALUE');active.add(v);try{if(Array.isArray(v)){if(Object.getOwnPropertySymbols(v).length||Object.keys(v).length!==v.length)fail('UNSUPPORTED_TYPE');return'['+Array.from({length:v.length},(_,i)=>{const d=Object.getOwnPropertyDescriptor(v,String(i));if(!d||!('value'in d))fail('UNSUPPORTED_TYPE');return enc(d.value)}).join(',')+']'}const proto=Object.getPrototypeOf(v);if(proto!==null&&proto!==Object.prototype)fail('UNSUPPORTED_TYPE');if(Object.getOwnPropertySymbols(v).length)fail('UNSUPPORTED_TYPE');const keys=Object.keys(v);if(Reflect.ownKeys(v).length!==keys.length)fail('UNSUPPORTED_TYPE');keys.forEach(scalarString);keys.sort((a,b)=>a<b?-1:a>b?1:0);return'{'+keys.map(k=>{const desc=Object.getOwnPropertyDescriptor(v,k);if(!('value'in desc))fail('UNSUPPORTED_TYPE');return encodeString(k)+':'+enc(desc.value)}).join(',')+'}'}finally{active.delete(v)}}return enc(value)}
export const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
export function instruction(value){canonical(value);if(value===null||typeof value!=='object'||Array.isArray(value))fail('INSTRUCTION_SCHEMA_INVALID');const expected=['contentSha256','domain','eventKey','observationIds','targetChannel'];if(Object.keys(value).sort().join('\n')!==expected.join('\n'))fail('INSTRUCTION_SCHEMA_INVALID');if(value.domain!=='horizon-publication-instruction-v1'||typeof value.eventKey!=='string'||!value.eventKey||typeof value.targetChannel!=='string'||!value.targetChannel||typeof value.contentSha256!=='string'||!/^[a-f0-9]{64}$/.test(value.contentSha256)||!Array.isArray(value.observationIds)||!value.observationIds.length||value.observationIds.some(x=>typeof x!=='string'||!/^[a-f0-9]{16}$/.test(x)))fail('INSTRUCTION_SCHEMA_INVALID');const normalized={...value,observationIds:[...new Set(value.observationIds)].sort()};const text=canonical(normalized);return {canonicalText:text,canonicalUtf8Hex:Buffer.from(text,'utf8').toString('hex'),instructionId:sha(Buffer.from(text,'utf8'))};}
export function instructionFromText(text){return instruction(strictParse(text))}
